### ISSUE TITLE
Automatically download typings in TypeScript projects

### ISSUE THREAD

**Issue by jcansdale** [Microsoft/nodejstools#1012]
On the wiki it says:

Types are automatically downloaded if all of the following are true:
You have a JavaScript project (not Typescript).
https://github.com/Microsoft/nodejstools/wiki/Automatic-Typings-Acquisition

I don't completely understand the difference between a JavaScript and a TypeScript project. They both have TypeScript item templates and TypeScript gets compiled into JavaScript for both. I was surprised to find that automatic downloading doesn't work for TypeScript project. TypeScript projects are where I'd expect to get Intellisense the most!

##### Expected Behavior 

TypeScript and JavaScript projects work the same.

##### Actual Behavior 

A useful feature only exists in JavaScript projects!

**Comment by mousetraps** [comment]
@jcansdale Yes, it is a bit ironic, isn't it :wink:

The reason we opted not to target TypeScript projects for auto-typings acquisition was because there's currently no good versioning story for TypeScript definition files, and because TS has stricter linting, the editor will actually throw errors when mismatched files are included, whereas in JS, it'll just provide less accurate IntelliSense. That said, I expect the experience to greatly improve now that TypeScript has started [loading typings that are bundled with npm packages](http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html). It'll just take some time to percolate through the ecosystem.

cc @DanielRosenwasser, @bowdenk7

**Comment by DanielRosenwasser** [comment]
Hey @jcansdale, we've got plans to make this easier for TypeScript in general, but there are some upcoming features it depends on (such as moving towards npm for declaration management) to avoid some of the issues @mousetraps mentioned.

**Comment by mousetraps** [comment]
Closing, since there's no good way to resolve at this point in time
