### ISSUE TITLE
Breakpoint doesn't hit / shows up at wrong place

### ISSUE THREAD

**Issue by pmadhur** [Microsoft/nodejstools#1023]
Hi,

NTVS version: 1.2.40329.01
Visual Studio version: 14.0.25123.00 Update 2 (Community 2015)
Node.js version: v6.1.0

Steps to Reproduce:

1. Create a new project using the template "Basic Node.js Express 4 Application".
2. Open index.js file in routes directory.
3. Set a breakpoint at line 6.
4. Press F5. Browse opens up, shows the page but the breakpoint is not hit.
5. Hit reload in browser, now the breakpoint is hit in app.js line 1.

Do I need to set some option so the breakpoint is hit at the desired location?

Regards,
Madhu.

![ntvs_breakpoint_err](https://cloud.githubusercontent.com/assets/16571328/15991595/750e41c0-30b7-11e6-8e76-4b26b243d668.gif)

**Comment by mjbvz** [comment]
Thanks for the report. Since you are Node 6.1, this look like another manifestation of #934 to me. Closing this issue in favor of that one.

We're still actively investigating the problem, but determine what has changed since Node 5.x regarding the Node debugging behavior has been difficult. It appears to be a timing issue of some sort right now.
