### ISSUE TITLE
Automatic brace completion property greyed out in TS, but not in Node.js

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1033]
We should grey it out in Node.js if ES6 mode is selected, otherwise it'll propogate a false value to TS.

**Comment by mjbvz** [comment]
Related to Typescript not supporting this feature: #1142

**Comment by mjbvz** [comment]
#1142 has been fixed by Typescript 2.0 RC https://github.com/Microsoft/nodejstools/issues/1142#issuecomment-245431874 and the values propagate properly (but, like the other settings, it is possible for Node and Typescript to get out of sync.)

I'll leave this open to track graying out the option on for lower typescript builds that do not support this.
