### ISSUE TITLE
REPL Window Reference Error after `c = "hello"`

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1035]
##### Expected Behavior

`c = "hello" // prints 
![image](https://cloud.githubusercontent.com/assets/762848/16027500/229e8358-318b-11e6-8159-29660dc5b5f8.png)
##### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/762848/16027477/ff5f8126-318a-11e6-8c7f-a1bc5c4a4280.png)

- NTVS Version: latest build from master

May be related to #1030

**Comment by mjbvz** [comment]
The reference error is expected since we now run the code in strict mode #876. The unexpected part is  that `c` still gets set even though the error is thrown.

We use `vm.runInContext` for evaluating repl commands. It could be that I'm just overlooking something stupid with how `vm.runInContext` or JavaScript works, but I opened a StackOverflow question to try to understand this behavior a little better: http://stackoverflow.com/questions/37801427/node-vm-runincontext-strict-mode-with-global-referenceerror-still-sets-global

**Comment by paulvanbrenk** [comment]
has the correct behavior now
