### ISSUE TITLE
Electron Application Debug support

### ISSUE THREAD

**Issue by emdadgar2** [Microsoft/nodejstools#1072]
Hi,
How we can debug electron applications?

**Comment by mjbvz** [comment]
Are you launching the electron app through VS or attaching onto a running electron app? Could you please share what current problems you are running into?

I believe that you may need to pass some additional flags to debug Electron apps. Right click the project and select properties. Then try adding:
* Script arguments: `--debug=5858 app`
* Node.js port: `5858`

**Comment by mjbvz** [comment]
Here's how to attach to an electron app and debug it with NTVS

1. Go to the electron app's directory.
2. Launch electron app with: `electron --debug-brk=5858 --nolazy .`
  This pauses the app to wait for the debugger to connect before actually running  it.
3. In VS, with electron project open in NTVS, go to `Debug -> Attach to Process`
4. Select:
 * Transport: `Node.js remote debugging`
 * Qualifier: `tcp://localhost:5858/#ping=0`
  
  The `#ping=0` part stops the debugger from connecting right away and starting the app.

5. Refresh the list to see the app:

![image](https://cloud.githubusercontent.com/assets/12821956/16249780/49d76a64-37cd-11e6-9f62-7cb3e28958ea.png)

6. Select app and hit `Attach`

This should allow you to debug the app in NTVS. Again, I'll investigate to see if you can launch the electron app through VS directly instead of attaching manually. Please let me know if you have any questions or run into any problems.

**Comment by emdadgar2** [comment]
There is another way:
[http://qiita.com/mt08/items/319a73f34d2b95c9dab8](http://qiita.com/mt08/items/319a73f34d2b95c9dab8)

**Comment by mjbvz** [comment]
@emdadgar2 Good to know, thanks for the link.

To summarize that approach:

1. Install Electron
2. Create an NTVS project in Visual Studio with a main electron file called `app.js`.
3. Get your electron path. You can use `$ which electron` to get the full path from the command prompt. **Make sure to grab the `electron.cmd` path.**
4. In Visual Studio, right click on the project file and open project properties.
5. Set `Node.exe path` to the full `electron.cmd` path. In my case, this was `C:\Users\matb.REDMOND\AppData\roaming\npm\electron.cmd`
6. Set `Script (startup file)` to `app.js`
7. 🚫 🐞 Start debugging  

That should enable more rapid iteration than attaching every time.

My main reservation with this method is that we use `Node.exe path` for more than just launching node and debugging. This is also how we look up which version of npm to use. By changing the `Node.exe path`, we may fallback to the wrong version of npm which may lead to odd behavior. 

I'll see if we can improve the experience.

**Comment by HarelAshwal** [comment]
LK"I

Electron is super popular framework.
Is there any native support for it in next releases?
Currently the only alternative is to migrate to VSCode (it doesn't make sense to "Attach to process" each time....)

more on this here:
https://github.com/electron/electron/issues/10638
