### ISSUE TITLE
NTVS 1.2 Beta Feedback

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1077]
Love it? Hate it? Let us know what you think!

**Comment by charliedavison** [comment]
We faced significant issues surrounding using VS2015 with NTVS, the product was great when it was stable long enough to actually get any work done, unfortunately despite your guys great efforts(We really appreciate it!) we never got to the bottom of what was causing our problem.

However, since we switched to using NTVS with the VS15 beta it's been smooth sailing, and all of the problems we originally faced seem to have been resolved which is fantastic!

**Comment by NoelAbrahams** [comment]
@mousetraps,

I am quite pleased with the stability improvements around debugging NTVS projects.

However, a lot of the work on improving intellisense doesn't really affect us because we use TypeScript (and therefore have JS intellisense turned off).

My number one issue has been #518 and this is a daily problem. So when I seen releases not really affecting the quality of my life I am not super excited.

But it is encouraging to see the new releases coming through.

**Comment by jcansdale** [comment]
@NoelAbrahams,

> My number one issue has been #518 and this is a daily problem. So when I seen releases not really affecting the quality of my life I am not super excited.

As a workaround it would be easy to write a "BatchExportRunner" that executes all exports as a single test (that reports to stdout and fails when one or more tests fail). You could quickly swap back to "ExportRunner" when working on a particular suite of tests.

**Comment by kant2002** [comment]
@mousetraps My personal issue is that NTVS becoming memory hog on TypeScript project and very often freezes.

**Comment by mjbvz** [comment]
@kant2002 What symptoms are you seeing specifically? Could you provide some memory usage numbers and a basic description of the Typescript project you are seeing these numbers in.

Also, is memory usage high but stable, or is it slowly increasing? Do you eventually run out of memory?

**Comment by mjbvz** [comment]
@NoelAbrahams Thanks for the feedback.

We really want to get around to #518 at some point, but have not been able to prioritize it yet. Anyone is free to start looking into the problem and start work on a solution though, and we are always happy to discuss design ideas and provide feedback or help.

**Comment by kant2002** [comment]
@mjbvz My project structure 

**With node_modules folder**

| Ext | Count |
|------|------|
|.ts   | 390 |
|.d.ts   | 317 |
|.js   | 11523 |


**Without node_modules folder**

| Ext | Count |
|------|------|
|.ts   | 385 |
|.d.ts   | 65 |
|.js   | 1169 |

Project is Express application with front-end written in Angular. JS files is not part of the project, I just include them to give you some statistics which may or may not be important for you.

**NTVS behavior**
- Very often VS has paused for couple seconds, not uncommon when this period could take up to 5-10 seconds.
- Opening single project take up to the minute. My .NET Core opens much faster and even faster opens the old-school C# projects. I think this issues not entirely related to NTVS, but maybe related to new project structure of VS. Don't know
- When build using external tool very often NTVS window pauses.
- After some time project start using more and more memory and pauses become more frequent. Restarting VS is very distracting to workflow, so I very often rely on VSCode which less powerful then VS.
- Running out of memory now does not happening, but I barely use VS for main work on that project, just using it for navigation across code, finding dependencies and when I need to produce code I half-time use VSCode and half-time use VS.

**Comment by kant2002** [comment]
@mjbvz or @mousetraps  any news why NTVS could freeze?

**Comment by mjbvz** [comment]
Closing since [NTVS 1.2 is now out](https://github.com/Microsoft/nodejstools/releases). Please try upgrading and sending us any feedback here: #1147 or open new issues for any bugs
