### ISSUE TITLE
Indentation of "chained" calls

### ISSUE THREAD

**Issue by danderson00** [Microsoft/nodejstools#108]
A common pattern for formatting "chained" calls is to place each new operation indented on a new line, for example:

    router.route('/tables/:tableName/:id')
        .get(function (req, res, next) {
            return tables.read(req.params.tableName, req.query)
                .then(function (results) {
                    res.send(JSON.stringify(results));
                    next();
                });
        })
        .post(function (req, res, next) {
            // do some stuff
        })

However, NTVS formats the code without the additional indentation:

    router.route('/tables/:tableName/:id')
        .get(function (req, res, next) {
        return tables.read(req.params.tableName, req.query)
                .then(function (results) {
            res.send(JSON.stringify(results));
            next();
        });
    })
        .post(function (req, res, next) {
            // do some stuff
    });

**Comment by mousetraps** [comment]
Great idea! I'll *very optimistically* assign it to the May milestone because I *think* there's a way to make this change without being too disruptive, and it you're right that this is super helpful from a code readability standpoint. Otherwise we'll take a look next time we're looking into formatter changes (we like to get those in early on in any release because the formatter is one of those areas that tends to break a bunch of other stuff when we touch it and we like having stabilization time.)

**Comment by mjbvz** [comment]
Fixed in NTVS 1.2 Alpha with ES6 Intellisense preview

![image](https://cloud.githubusercontent.com/assets/12821956/14508635/48c0c64c-017d-11e6-8c71-89578611ca8d.png)
