### ISSUE TITLE
Hint about downloading Typings does not hide from Solution Explorer when NTVS project closed.

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#1109]
##### Expected Behavior 
Solution explorer should not display unreleated hints to project which not related to NodeJS

##### Actual Behavior 
Solution Explorer displays the text 'NodeJS Intellisense added a typings folder'
![image](https://cloud.githubusercontent.com/assets/4257079/16377919/b752ff24-3c8a-11e6-8076-f755641482c7.png)

- NTVS Version: NTVS 1.2 Beta
- Visual Studio Version: VS2012 Update 3

##### Steps to Reproduce
1. Create NodeJS Javascript console project
2. Wait while mwarning about typings appear
3. Create New Cordova project without closing VS.

**Comment by mjbvz** [comment]
Thanks for the report.

This is a bug, but I'm not sure its worth trying to fix, since users can easily dismiss the bar or even disable these alerts entirely by going to `Tools -> Options` and `Node.js -> IntelliSense` and disabling `Show status bar after adding new typings folder to project.`.

My concern with any code fix are the edge cases, such as multiple, mixed projects solutions. It does not seem worth the additional complexity.
