### ISSUE TITLE
Which files should be committed

### ISSUE THREAD

**Issue by mwpowellhtx** [Microsoft/nodejstools#1129]
And the debate continues over which files to commit to source, whether the whole ``node_modules`` is required, or just what exactly is required. Clearly something is, because when I ignore ``node_modules``, I clone from my Git repository and the installed modules aren't there, much less any of their dependencies.

**Comment by mjbvz** [comment]
What problem are you trying to solve? General development? Deployment?

I advise against including `node_modules` in your git repo. It's unnecessary since any developer or tool should be able to clone your code and install all the node modules from your `package.json` by running  `$ npm install`. 

For common use cases, including `node_modules` at best adds bloat and muddies up source history, but can also introduce fun when dealing with native modules.

**Comment by mwpowellhtx** [comment]
I want to commit only the necessary files to Git (or other source control) such that I can clone and recall the npm package references.

**Comment by mjbvz** [comment]
All the packages you need should be tracked by the `package.json`. To test this, delete your `node_modules` folder and run `$ npm install` again for the project. It should recreate `node_modules`. If the project no longer works, you need to fix the `package.json`.

That's why I recommend against including `node_moduldes` in source control in almost all cases. Any developer or tool should be able to recreate it.

**Comment by mwpowellhtx** [comment]
I don't recall the option precisely, but it was something like project only, or something like that. Anyway, I commit the ``package.json``, and even the recursive ones, and this does not restore, or I have missed a file necessary to commit.

**Comment by mjbvz** [comment]
If you are working in a single project, chances are you only need the top level `package.json`. This should list all the dependencies for your project.

You ran `npm install` again, correct? What does your `package.json` look like? What files are missing after `npm install`?

**Comment by mwpowellhtx** [comment]
Okay, so there is a _"package@version (not listed in package.json)"_ in my ``npm`` section. I want to retain that feature about the project.

**Comment by mjbvz** [comment]
That circumvents the purpose of listing `dependencies` in `package.json`. What is the reasoning? Is it  private?

If you *really* need to have a package in `node_modules` but not in the `package.json`, you could configure the `.gitignore` file like this:

```
node_modules/
!node_modules/package-to-be-included-in-project/
```

**Comment by mwpowellhtx** [comment]
I see, I understand, thanks.
