### ISSUE TITLE
List commands from package.json in Task Runner Explorer

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#1138]
Maybe not NTVS related, but I think good use case.

Right now Task Runner Explorer show tasks only for Gulp/Grunt.
NPM is also valid case for running tasks. I think about that since this give me quick workaround for #1137, I could run NPM task which run test suite and temporary would be all set.

That's seems simple and if this is not NTVS related, but rather work for other team, if you could point me another repository where I could land some code I would very appreciate it.

**Comment by mjbvz** [comment]
Not directly part of NTVS currently, but take a look at this VS plugin: https://visualstudiogallery.msdn.microsoft.com/8f2f2cbc-4da5-43ba-9de2-c9d08ade4941

It seems to offer the functionality you describe.

**Comment by kant2002** [comment]
@mjbvz Cool extension, will check it out, maybe it is good extension to promote in Wiki as complementary too to NTVS.

**Comment by kant2002** [comment]
@mjbvz  I try it out, it really exact what I want. 
I think it is good to be promoted on this Wiki page https://github.com/Microsoft/nodejstools/wiki/npm-Integration
I don't know about your legal limitatoins, but that extension is really complimentary to NTVS suite and it is right place to have it in Wiki.

**Comment by mjbvz** [comment]
I've add the npm task runner to our list of other recommended extensions: https://github.com/Microsoft/nodejstools/wiki#recommended-extensions


Since there is an existing extension with this functionality, this is likely not a feature we will prioritize anytime soon, but anyone is welcome to contribute this functionality to NTVS. Please let me know if would like help planning this or need any assistance getting started.

**Comment by paulvanbrenk** [comment]
Added the npm scripts to "Open Folder", so there's now 2 ways to invoke these commands.
