### ISSUE TITLE
Microsoft.NodejsTools.Repl.ReplWindowProvider error

### ISSUE THREAD

**Issue by pavparx** [Microsoft/nodejstools#1162]
I just installed the tools and when I open the node.js interactive window I get  [this error](https://gyazo.com/d8202afedba50bbf5a6fadffbe2362cb)

- NTVS Version:1.2.rc.vs.2015
- Visual Studio Version: 14.0.25424.00 update 3
- Node.js Version: 3.10.3

##### Steps to Reproduce
1. Install ntvs.1.2.rc.vs2015
2. Open node interactive window

**Comment by mjbvz** [comment]
Thanks for reporting this.

This is a high priority known issue that is currently blocking the release of NTVS 1.2. Did you upgrade from NTVS 1.1?

As a workaround, please try deleting the `%localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache` directory. We believe the root cause is that Visual Studio is caching something and still referring to an old copy of NTVS. Just running `devenv.exe /setup` did not fix the problem in my testing, but that may be worth trying as well.

Please let me know if that works.

Thanks.

**Comment by pavparx** [comment]
Deleting the ComponentModelCache directory did the job. I hadn't upgraded from ntvs 1.1, I did a clean install. Before, installing ntvs 1.2 rc, I had installed and tried npm task runner and package installer,then I uninstalled these and tried NTVS 1.2RC, maybe there was a conflict with these previous nuget packages. Thanks for replying and helping me out.
