### ISSUE TITLE
[VS15 lightweight] Cannot Find RemoteDebugProxy folder

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/nodejstools#1179]
##### Repo
On VS 15 with lightweight install:

Go to `Tools -> Node.js Tool -> Remote Debug Proxy -> Open Containing Folder`

##### Expected
Opens folder

##### Actual
Message about how the folder cannot be found.

**Comment by mjbvz** [comment]
RemoteDebugging depends on a shared registry location, and we likely need to change this to properly support lightweight install:

https://github.com/Microsoft/nodejstools/blob/511039b9f2007e54d00d6afc6bb2a4835fcd49af/Nodejs/Setup/NodejsTools/NodejsTools.wxs#L45

**Comment by mjbvz** [comment]
@mousetraps What is the reason for storing the path to`RemoteDebug.js` in the registry? Why is this file handled differently than the test framework javascripts for example?

**Comment by mousetraps** [comment]
@mjbvz my best guess is that once upon a time, we copied some pattern that PTVS was using in its installer... and PTVS, in turn, had been using this pattern because they installed the debug assembly in the GAC, which meant the assembly wouldn't live side-by-side with the rest of the files. In our case, it shouldn't make any difference.

**Comment by mjbvz** [comment]
This command now opens the correct folder in VS15 Preview 5
