### ISSUE TITLE
Typings produce unexpected errors

### ISSUE THREAD

**Issue by benquarmby** [Microsoft/nodejstools#1188]
##### Expected Behavior

Typings for NPM modules do not produce any errors.
##### Actual Behavior

Typings for NPM modules produce unexpected errors.

- NTVS Version: 1.2.40726.00
- Visual Studio Version: 14.0.25424.00 Update 3
- Node.js Version: 4.4.5
##### Steps to Reproduce
1. Create a new project using the Blank Node.js Console Application template.
2. From the Install New npm Packages dialog, install `fs-extra-promise` version 0.4.0
3. Wait a short amount of time
4. Observe errors in Visual Studio Error List:
   ![image](https://cloud.githubusercontent.com/assets/1434816/17348502/def57ea8-5959-11e6-823d-21605d36423b.png)

**Comment by mjbvz** [comment]
Thanks.

This unfortunately is the expected behavior at the moment. [We use `typings` and `*.d.ts` files to power our modern IntelliSense experience](https://github.com/Microsoft/nodejstools/wiki/Automatic-Typings-Acquisition), and this experience mirrors what you would run into manually installing these typings files by running `typings install dt~fs-extra-promise --global`.

```
>typings install dt~fs-extra-promise --global
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a44332a250f703db51a79b2befd635ca9f38b15c/node/node.d.ts" during installation from "fs-extra-promise" (main)
typings INFO reference Stripped reference "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a44332a250f703db51a79b2befd635ca9f38b15c/bluebird/bluebird.d.ts" during installation from "fs-extra-promise" (main)
fs-extra-promise
└── (No dependencies)
```

[The `fs-extra-promise.d.ts` file references bluebird](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/fs-extra-promise/fs-extra-promise.d.ts) but we do not follow or install this reference automatically and, as far as I know, `typings` does not have an option to download these automatically either. The current workaround would be to manually install the bluebird typings file: `typings install dt~bluebird --global`


The whole typings experience will be improved in VS15, but if anyone wants to take a look at this problem, please let me know. Here's the wrapper script we use to acquire typings: https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/TypingsAcquisitionTool/index.js We should be able to look for those reference stripped events and handle them correctly.

**Comment by benquarmby** [comment]
Thanks for the detailed info. Makes sense.

This was just an example by the way, but I've seen quite a few different errors (not just "Could not find module") due to `d.ts` conflicts etc.

We may choose to disable typings integration in the immediate term and live without the richer intellisense. Really can't have these errors mingling with real errors in our solution. Ignoring items in the Error List in Visual Studio is a slippery slope.

**Comment by paulvanbrenk** [comment]
This doesn't look like an actionable bug at this time
