### ISSUE TITLE
Autoclose quotes?

### ISSUE THREAD

**Issue by michaelpittino** [Microsoft/nodejstools#1207]
Hello! I'd like to know if it is somehow possible to autoclose quotes.
Like if I type `require('` it should automatically add a second `'` and place the cursor in between like VS does in C#.

Thanks!

**Comment by mjbvz** [comment]
I believe this is another manifestation of #1142. The root cause is that, with NTVS 1.2, our editor and IntelliSense are now powered by Typescript. This switch regressed some functionality over NTVS 1.1 but should provide a much better experience in the long run.

I'm following up with the Typescript team to verify this is something they are handling and to see if there is any pre-release TS builds for VS2015 that have this feature enabled.

**Comment by mjbvz** [comment]
Closing as a duplicate of #1142 so that everything is tracked in a single location.

Thanks.
