### ISSUE TITLE
How can I run `npm test` from VS?

### ISSUE THREAD

**Issue by pps83** [Microsoft/nodejstools#1240]
I'm using this sample project: https://github.com/addaleax/playback-stream.git
I open it in VS as nodejs project from existing source code.

If I do it all manually then I can do `npm test` and it works. How can I get it to work in VS and its test explorer? Shouldn't it check package.json and figure out what should be done for `npm test`?

The other questions: how can I debug the unit tests (inside `test/index.js`)? If I try to step through I'm getting "ReferenceError: describe is not defined". In test/index.js in file properties I set TestFramework to Mocha and it discovers and runs the tests, but if I try to run tests with debugger it doesn't work.

**Comment by mjbvz** [comment]
NTVS only support integration with the [Visual Studio Test explorer by marking the unit test files](https://github.com/Microsoft/nodejstools/wiki/Test-Explorer), not by picking them up through `npm test`. That command just runs a script to invoke the tests, and our current model does not support building a list of unit tests from the output of a script like this.

You can of course just run `.npm test` from the [NodeJS interactive window](https://github.com/Microsoft/nodejstools/wiki/Interactive-Window-(REPL)) but that does not have any integration with the VS test explorer.

I'm unable to repo the test debugging issue you describe. Are you right clicking on the target test in the test explorer and selecting `Debug Selected Tests`? If you just run `node test/index.js`, mocha tests will not work because `describe` is used as a global. Could please you provide step by step instructions so I can investigate? 

Thanks.

**Comment by pps83** [comment]
Yes, it was a mocha test and I found it hard to figure out how to simply run these tests in VS debugger (I'm not a nodejs expert). In WebStorm it was easier, as there is a target for running mocha tests.
I'm not as much interested in integration with test explorer as I'm interested in ability to handle most common test suites as a normal nodejs app and step through it with VS debugger. Most common are mocha and a few other similar ones, that would cover 95% of the use cases

**Comment by paulvanbrenk** [comment]
Closing as this is outside the scope of the test explorer. Though we are planning on some work to make integration with unit test frameworks more straight forward.
