### ISSUE TITLE
outDir and rootDir does not work for tests or debugging of TypeScript

### ISSUE THREAD

**Issue by lostfields** [Microsoft/nodejstools#1243]
##### Expected Behavior

Debugging of TypeScript should work with outDir + rootDir in tsconfig
##### Actual Behavior

Throws an error complaining that corresponding javascript file isn't found

- NTVS Version: 1.2.40627.01
- Visual Studio Version: 14.0.25422.01 Update 3
- Node.js Version: 6.3.0
##### Steps to Reproduce
1. Create a "Blank NodeJS Console Application"
2. Move "app.ts" into folder "src"
3. Add "tsconfig.json"

``` json
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs",
        "declaration": true,
        "sourceMap": true,
        "outDir": "./build",
        "rootDir": "./src"
    },
    "exclude": [
        "build"
    ]
}
```
1. Set a break-point in app.ts 
2. Start debugger and an error is thrown. Notice that outDir and rootDir isn't respected.

``` bash
Debugger listening on [::]:5858
 module.js:442
    throw err;
    ^

Error: Cannot find module '[project-path]\src\app.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Timeout.Module.runMain [as _onTimeout] (module.js:575:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
 Press any key to continue...
```
1. Disable tsconfig.json for a bit, and open "Project properties", and set outputdir to "./build" and root dir to "./src".
2. Re-enable tsconfig.json
3. Debug again and an error is thrown. Now is outDir respected, but debugger does not know of our rootDir as it looking for \build\src\app.js and not \build\app.js

```
Debugger listening on [::]:5858
 module.js:442
    throw err;
    ^

Error: Cannot find module '[project-path]\build\src\app.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Timeout.Module.runMain [as _onTimeout] (module.js:575:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
 Press any key to continue...
```

**Comment by mjbvz** [comment]
@lostfields 
Thank you for reporting this.

It looks we do not properly pick up typescript project properties in the case where a `tsconfig.json` file exists. When getting the name of the js file to launch, `TypeScriptOutDir` always returns null (unless it has been previously set, but this function will still not return the value from the `tsconfig.json` ever): https://github.com/Microsoft/nodejstools/blob/86327f9bf3ce5789bc2ed4f1923dee21e06623d0/Nodejs/Product/TypeScript/TypeScriptHelpers.cs#L37

We have the same core problem `rootDir`, but I don't think we support `rootDir` at all right now.


@billti, @jasonra
For Typescript, since the `tsconfig.json` file appears to be the source of truth for Typescript projects, is there any way to access project properties that files defines from NTVS? I'd like to avoid adding custom logic to parse and understand `tsconfig.json` files on our side if possible.

**Comment by lostfields** [comment]
I really hope this get fixed soon as this makes my npm packages a lot cleaner and a lot nicer when referencing sub modules. If I'm naming outDir 'lib' instead it will be like 'import .... from "my-npm-package/lib/app"'. Looks a lot nicer than typing 'my-npm-package/lib/src/app'.

**Comment by lostfields** [comment]
I think this is related to #1241 where Test Explorer/Mocha can't discover the tests.

**Comment by ZenSoftware** [comment]
I am experiencing this particular bug as well.  `outDir` and `rootDir` within `tsconfig.json` are not being respected when launching the debugger in VS Enterprise 2015.  VS will try to launch a non-existent script.  Specifically it tries to execute the transpiled "Node.js Startup File" in the path that is directly adjacent to the source, instead of in the `outDir`.  I'm not too sure how to correct this.

**Comment by lostfields** [comment]
@ZenSoftware for now, disable tsconfig and try to apply the same settings to "Project > Properties" under "TypeScript Build" and then enable your tsconfig again.

**Comment by lostfields** [comment]
Ahhh.... please fix this for Visual Studio 2017 with inbuilt typescript. Where do I report that

**Comment by lostfields** [comment]
still not fixed :-(

**Comment by paulvanbrenk** [comment]
This looks like it's much more work than I expected. Closing in favor for #1949 which captures more use cases.

**Comment by KhoiNguyenICT** [comment]
Can't you help me fix this ?. I change outDir but my vs push notification program can't not file app.js in source dist '.'. Thank you so much.
