### ISSUE TITLE
If First Push to Azure is Debug configuration, site is not configured correctly

### ISSUE THREAD

**Issue by jsandersrocks** [Microsoft/nodejstools#1247]
##### Expected Behavior

First Deploy if Debug is set should create the correct directory structure and do npm to create node packages
##### Actual Behavior

First Deploy if Debug is set, the files are copied up and that is it.
Site will not run

- NTVS Version: 1.2.40726.00
- Visual Studio Version: 2015 Update 3
- Node.js Version: N/A default
##### Steps to Reproduce
1. Create a new Node.js Azure App
2. Deploy to new Azure App Service setting Build type to Debug

**Comment by mjbvz** [comment]
Thanks. The problem seems to be that Azure is not running `npm install` automatically after the deployment through visual studio. If you setup up continuous deployment from git or elsewhere, this seems to work, but not when deploying directly through vs.

I'm not sure where exactly the problem lies, or if this is expected or not. This could be from the publish logic in VS or something in azure. And NTVS may somehow be triggering all this.

As a workaround, you can locally npm install all packages before publish through VS or use CI. The local install method will only work if there are no native modules though.

Will investigate further.

**Comment by paulvanbrenk** [comment]
We're re-evaluating our support for publishing to Azure, current thinking is to suggest users use either git-publishing or the azure CLI.
