### ISSUE TITLE
express - debug client side javascript

### ISSUE THREAD

**Issue by HarelAshwal** [Microsoft/nodejstools#1279]
Hi All,

Is there any plan to add client side javascript debugging capability for express ?

see below:
http://stackoverflow.com/questions/26547398/can-visual-studio-2013-debug-clientside-javascript-in-a-nodejs-web-application

Harel

**Comment by mjbvz** [comment]
We don't have any definite plans around this, but here's our current plans for the debugger and some thoughts on how we could support this scenario.

Node is in the process of replacing the old V8 debug protocol with the Chrome debug protocol. If we can support that, we would be able to debug client apps running in Chrome.

Rather than rewrite our debugger from the ground up to use the Chrome debug protocol, we plan on moving the NTVS debugger to use [the vscode debug protocol](https://github.com/Microsoft/vscode-debugadapter-node). That may allow us to talk to chrome using something like the [vscode-debug-adapter for chrome](https://github.com/Microsoft/vscode-chrome-debug). But again, client debugging is not a focus.

If you are looking for solid IDE that can debug both Node and client apps today, I recommend [Visual Studio Code](http://code.visualstudio.com).

Please let me know if you have any other thoughts or ideas here.

Thanks.
