### ISSUE TITLE
Visualizer for Map object

### ISSUE THREAD

**Issue by HarelAshwal** [Microsoft/nodejstools#1305]
LK"I

Hi ,

Have you considered adding visualizer for ES6 Map object?

Harel

**Comment by mjbvz** [comment]
Yes, we want to add this since the current debugging experience for `Map` and `Set` is very poor.

We're currently investigating switching to use a debugger that interfaces with the VSCode node debug engine. This will allow us to automatically pick up features like this, and also allow us to better support new Node.js releases (especially once Node.js removes the old V8 debug protocol entirely). Look for work on this in the coming months.

Thanks.

**Comment by paulvanbrenk** [comment]
Closing as we won't be adding this to the Node 6 debugger, and we use the VS Code debugger for Node 8.
