### ISSUE TITLE
Intellisense for nodejs not working

### ISSUE THREAD

**Issue by Bhushan001** [Microsoft/nodejstools#1323]
I have recently installed visual studio 2015.

I have also installed nodejs tools for visual studio 2015 from its official source:

[Visual Studio tools for nodejs](https://www.visualstudio.com/vs/node-js/)

Now I am able to create nodejs-express 4 projects inside visual studio 2015.
I am able to do npm operations inside my editor too.

But I am not able to make intellisense working.

it does not show code suggestions.

Do I have to enable it manually?

I tried few blogs and tried to edit from :

Tools => Options => Text Editor => NodeJs 

but there is no nodejs option to configure.. only javascript is there.

[![Screenshot of my editor configurations](http://i.stack.imgur.com/CyqBh.png)](http://i.stack.imgur.com/CyqBh.png)

Also When I run npm install from my IDE , after installing node_modules it shows this message:

> Could not find Typings package manager tool used for Intellisense

any inputs?

thanks

**Comment by mjbvz** [comment]
Interesting. IntelliSense should be active by default but since Node.js is not listed in the options menus, your NTVS install may be messed up.

Can you please provide the output from `Help -> About Microsoft Visual Studio`. Use the `Copy Info` button. I want to see if NTVS is properly registered as an extension. 

Thanks.

**Comment by mjbvz** [comment]
Closing since I have not heard anything back on this. Please let me know if you are still running into this problem. Thanks.

**Comment by ltung** [comment]
Hi @mjbvz,

I want to follow up since I have exactly the same problem as @Bhushan001 

Here is my "Copy Info":

`Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Architecture and Modeling Tools   00322-90150-00888-AA941
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Microsoft Visual Studio Tools for Applications 2015   00322-90150-00888-AA941
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-90150-00888-AA941
Microsoft Visual Basic 2015

Visual C# 2015   00322-90150-00888-AA941
Microsoft Visual C# 2015

Visual C++ 2015   00322-90150-00888-AA941
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-90150-00888-AA941
Windows Phone SDK 8.0 - ENU

ApexSQL Refactor   1.0
ApexSQL Refactor Visual Studio Addin Component

Application Insights Tools for Visual Studio Package   7.10.01020.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20907.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9.5   14.0.20810.0
Azure App Service Tools v2.9.5

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.1.0000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Git Source Control Provider   1.6.5.1


GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2016.2.2    Build 106.0.20160913.91321
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft .NET Core Tools (Preview 2)   14.1.20907.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Hive Query Language Service   2.1.0000.0
Language service for Hive query

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40715.2

Node.js Tools   1.2.40726.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.2.40726.00
Profiling support for Node.js projects.

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.40825.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.40825.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.40825.00
Profiling support for Python projects.

SQL Server Analysis Services   13.0.1700.68
Microsoft SQL Server Analysis Services Designer 
Version 13.0.1700.68

SQL Server Data Tools   14.0.60812.0
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 13.0.1601.5

SQL Server Reporting Services   13.0.1700.68
Microsoft SQL Server Reporting Services Designers 
Version 13.0.1700.68

TestAddin   1.0


ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

Visual Studio Tools for Apache Cordova   Update 10
Visual Studio Tools for Apache Cordova

Visual Studio Tools for Universal Windows Apps   14.0.25527.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Web Compiler   1.11.319
Compiler for LESS, Sass and CoffeeScript files

Xamarin   4.1.1.3 (34a92cd)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.1.1.1 (7db2aac)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.iOS   9.8.1.4 (3cf8aae)
Visual Studio extension to enable development for Xamarin.iOS.`

**Comment by mjbvz** [comment]
@ltung Thanks.

In Visual Studio, if you go to `Tools -> Options` is there any `Node.js` section listed under `Text Editor`? Do you see any `Node.js Tools` section in the VS `Tools` menu?

From a visual studio developer command prompt, you can also try running:

```
devenv /setup
```

To try fixing a bad NTVS installation. If that still doesn't work, run:

```
devenv /log
```

and share the `%appdata%\Microsoft\VisualStudio\14.0\ActivityLog.xml` file. This will help us investigate what may be going wrong.

Thanks.

**Comment by sldev2** [comment]
I do not have intellisense in VS 2015, in nodejs projects, even after un-installing, and then rerinstalling Node.js Tools 1.2 for Visual Studio 2015 

Actually, there's a "mini" intellisense, with the heading, "Autoselect disabled due to potential declaration"

![image](https://cloud.githubusercontent.com/assets/4023261/20826172/10c603da-b837-11e6-816a-da664902e9bb.png)

**Comment by sldev2** [comment]
I ran devenv /setup, but that didn't fix anything.

My "copy info"

Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA972
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-80000-00000-AA972
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA972
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA972
Microsoft Visual C++ 2015

.NET Reflector Visual Studio Extension   9.0.1.374
Integrates .NET Reflector into Visual Studio to allow you to seamlessly debug into third-party code and assemblies, even if you don't have the source code for them.

Visit www.reflector.net for more information.

Copyright (c) 2009-2012 Red Gate Software Inc.

Application Insights Tools for Visual Studio Package   7.14.01128.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

ConfigurationTransform   1.3
Automatically transform app.config during build process. Once the transformation is set, it will run on other build machines without the extension.

EditProj   1.0
This packages allows you to edit project files without the need to unload them first.

Favorite Documents   2.2
Favorites menu for Visual Studio IDE.

File Nesting   1.0
Automatically nest files based on file name and enables developers to nest and unnest any file manually

GitHub.VisualStudio   2.1.1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

GitPlugin Extension   1.0
GitPlugin Visual Studio Extension Detailed Info

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

MZ-Tools   8.0.0.115
MZ-Tools productivity plug-in for Visual Studio. For more information, visit http://www.mztools.com

Node.js Tools   1.2.40726.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.2.40726.00
Profiling support for Node.js projects.

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Show Missing Files   1.0
Find files references in project files that don't exist on disk, and optionally files that do exist on disk that aren't included in a project. 
Runs on Build. Missing files are listed in Error List window.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   2.0.6.0
TypeScript tools for Visual Studio

Web Essentials 2015.3   3.0.235
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by skybo053** [comment]
I recently installed NodeTools for VS 2015, and I am having this same problem.  Once I use the npm to install the appropriate packages, I get no typings that download automatically.

After much trial and error, I found that I can use the command prompt to install the packages with "npm", and then to get intellisense I install the typing with "typings install package_name", and this will create a typings.json file in my solution explorer, and I will have intellisense.

I'm glad I have the intellisense working, but it seems like something isn't working quite right.

**Comment by infoGraphMT** [comment]
I think I have the same problem:

====Executing command 'npm install "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Node.js Tools for Visual Studio\1.2\TypingsAcquisitionTool"  '====

npm WARN package.json ntvs-typings-acquisition-tool@1.0.0 No repository field.
ntvs-typings-acquisition-tool@1.0.0 ..\..\..\..\..\node_modules\ntvs-typings-acquisition-tool
├── minimist@1.2.0
└── typings-core@1.3.1 (array-uniq@1.0.3, thenify@3.2.1, zip-object@0.1.0, popsicle-status@2.0.0, popsicle-retry@3.2.1, listify@1.0.0, promise-finally@2.2.1, xtend@4.0.1, throat@3.0.0, graceful-fs@4.1.11, lockfile@1.0.3, string-template@1.0.0, any-promise@1.3.0, typescript@1.8.7, strip-bom@2.0.0, sort-keys@1.1.2, has@1.0.1, make-error-cause@1.2.2, debug@2.6.1, rc@1.1.7, mkdirp@0.5.1, configstore@2.1.0, object.pick@1.2.0, invariant@2.2.2, parse-json@2.2.0, touch@1.0.0, detect-indent@4.0.0, is-absolute@0.2.6, popsicle-proxy-agent@3.0.0, popsicle@8.2.0, rimraf@2.6.1)

====npm command completed with exit code 0====

Could not find Typings package manager tool used for Intellisense
Could not find Typings package manager tool used for Intellisense

**Comment by billti** [comment]
This is quite possible the same issue #1464, as I see you also have a later TypeScript installed (2.0.6 above). Unfortunately there's an issue in NTVS if you clean installed a recent dev build (i.e. didn't upgrade), and an issue in TypeScript due to a change in how it determines context. The first can be worked around with a single registry addition, the second with a tsconfig.json file in the project root. Both are documented in the above issue, starting at comment https://github.com/Microsoft/nodejstools/issues/1464#issuecomment-283572619 .

We'll reissue both TypeScript and NTVS shortly to address both problems. I'll update both these issues when we do. Sorry for the inconvenience.

**Comment by paulvanbrenk** [comment]
This should work as expected now in v1.3 and Visual Studio 2017
