### ISSUE TITLE
NTVS affect performance of Visual Studio

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#1324]
##### Expected Behavior 
Some how NTVS slow VS startup.

##### Actual Behavior 
![image](https://cloud.githubusercontent.com/assets/4257079/19220690/3ab4cb38-8e55-11e6-901a-35932f6b0bec.png)

- NTVS Version: Shipped with VS 15 Preview 5
- Visual Studio Version: VS 15 Preview 5
- Node.js Version:

**Comment by mjbvz** [comment]
This should be fixed in VS15 RC.

Visual Studio Preview 5 seems to have become stricter with startup and solution load checks and NTVS used to be incorrectly loaded eagerly, and I believe triggered these in VS15. The NTVS packages should now be loaded on demand. We've also reduced the amount of work NTVS does on when it loads.

Thanks. Please let me know if you still see these warnings once RC comes out.
