### ISSUE TITLE
No Intellisense When Using Browserify

### ISSUE THREAD

**Issue by ryanelian** [Microsoft/nodejstools#1370]
##### Expected Behavior 

Intellisense for modules loaded via `require()` syntax appears.

##### Actual Behavior 

No Intellisense appears.

- NTVS Version: 1.2
- Visual Studio Version: 14.0.25431.01 Update 3
- Node.js Version: 6.9.1

##### Steps to Reproduce
1. Develop an ASP.NET Core MVC application that uses Browserify for managing JavaScript project structure.
2. Use Visual Studio 2015U3 with NTVS 1.2
3. No intellisense appears when using `require()`.

Logically, since Browserify uses CommonJS module loaded from node_modules folder, Intellisense via this tooling should readily appears to aid you when developing your web application such as AngularJS.

Is there any specific options I need to tweak to enable this feature?

**Comment by mjbvz** [comment]
Thanks for the report.

Is the project you are working with an NTVS project or is it an asp.net project with node/JavaScript code? How was the project originally created?

**Comment by ryanelian** [comment]
Project was originally created as ASP.NET Core MVC project, then I dropped in [my own gulpfile](https://github.com/ryanelian/ryan-compiler/blob/master/gulpfile.js) to work with CommonJS-based [client-side project](https://github.com/ryanelian/ryan-compiler/blob/master/assets/js/index.js).

Which is actually fine and cool until you realized you don't get Intellisense from Visual Studio for doing something like `require('jquery')`. Apparently installing NTVS don't help in this aspect (even though logically it should because CommonJS), hence this issue.

**Comment by mjbvz** [comment]
Yes, since this is an ASP project, NTVS does not come into play here. We are only activated for Node.js projects (which are typically projects created starting from one of the JavaScript/TypeScript Node.js templates in VS).

You'll probably want to follow up with ASP.NET on this problem. [This repo](https://github.com/aspnet/Home) may be a good staring place.

Closing as external

**Comment by ryanelian** [comment]
Can't you guys just activate the Intellisense for ASP.NET project? (I'm not actually sure if Intellisense managed by the Visual Studio or the NTVS, but hey won't hurt to ask)

I mean, I don't really need any other features except the Intellisense in this case, which would be very helpful.

**Comment by mjbvz** [comment]
@ryanelian Our IntelliSense is [powered by the TypeScript project](https://github.com/Microsoft/TypeScript/wiki/Salsa). NTVS does a bit of work to make TypeScript picks up NTVS project files, but all of our IntelliSense is coming from Typescript. 

As far as I know, you should have IntelliSense in javascript files in an Asp.net project, but NTVS is not involved in that scenario at all. That's why I suggest you follow up with Asp.net directly. Someone there should be able to help you look into this problem.

This Typescript guide may also provide some ideas to try: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/tutorials/ASP.NET%20Core.md
