### ISSUE TITLE
Support for DeprecationWarning in Exception Settings window

### ISSUE THREAD

**Issue by kant2002** [Microsoft/nodejstools#1420]
##### Expected Behavior 
Would be very good to have DeprecationWarning behave as exception, and trigger pause on the application execution. It will allow very fast catch what piece of code introduce such warnings.

##### Actual Behavior 
DeprecationWarning just print in the console, and no information about file in which that warning is provided.

![image](https://cloud.githubusercontent.com/assets/4257079/20347131/e7c021f0-ac29-11e6-8397-cd538ee42065.png)

**Comment by billti** [comment]
Interesting idea. I see in in the 7.* releases they now call process.emitWarning instead of the prior behavior (see https://github.com/nodejs/node/commit/15eaba98a1 ). According to [the docs](https://nodejs.org/dist/latest-v7.x/docs/api/process.html#process_process_emitwarning_warning_name_ctor), you can listen for `process.on("warning")`, so we could potentially have a breakpoint/handler for any warnings.

**Comment by paulvanbrenk** [comment]
Tracking this in the issue DB for the node 8+ debugger.

**Comment by kant2002** [comment]
@paulvanbrenk where it is tracked? Please point to the repository, so I could keep going there and keep nagging these people.
