### ISSUE TITLE
Build Fails After Importing Project With tsconfig.json

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/nodejstools#1443]
Expects tsconfig.json to be in a different location.

##### Expected Behavior 
build successfully
##### Actual Behavior 
fails:

```

------ Build started: Project: ElectroniApp2, Configuration: Debug Any CPU ------
tsc(0,0): error TS5058: Build:The specified path does not exist: 'c:\users\arozga\documents\visual studio 2017\Projects\ElectroniApp2\tsconfig.json'
Done building project "ElectroniApp2.njsproj" -- FAILED.

Build FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

- NTVS Version:
- Visual Studio Version: 
- Node.js Version: 

##### Steps to Reproduce
1.  Create a project with a tsconfi.json and ts file*
2.  Open VS, create new project using TypeScript -> From Existing Node.js code
3. Build.

* Try doing the following in powershell:
```
mkdir c:\repo
cd c:\repo

# Clone the Quick Start repository
git clone https://github.com/electron/electron-quick-start

# Go into the repository
cd electron-quick-start

mv main.js main.ts

# add tsconfig.json
$tsconfig = @"
{
  "compileOnSave": true,
  "typeAcquisition": { "enable": true },
  "compilerOptions": {
    "module": "commonjs",
    "outFile": "main.js"
  }

}
"@
$tsconfig | add-content -path ./tsconfig.json

# Install the dependencies
npm install
```

**Comment by nhadro** [comment]
I am having this same issue.  Any resolution?  I wasn't sure what the bottom powershell was for?

**Comment by Faheetah** [comment]
Can this be made more intuitive? First I have the problem OP does, where it sounds like the files would be copied since they are being "imported" into the project, then I try to create a new one and end up getting myproject/myproject/NewNodeApp1.js or something. I would expect an IDE to allow me to just either open up the folder and specify what type of project it is and create the necessary editor files, or have "convert to project" option for a given folder.
