### ISSUE TITLE
Get Unknow function name when profiling Node.js application in Visual Studio 2015

### ISSUE THREAD

**Issue by SupporterMan** [Microsoft/nodejstools#1458]
**Expected Behavior:**
Get all function name in profiling report with their profiling data.

**Actual Behavior:**
All function names show as Unknown,

- NTVS Version: Both 1.2 and 1.1
- Visual Studio Version:  Both Visual Studio 2015 and Visual Studio 2013
- Node.js Version: 6.9.4

##### Steps to Reproduce
Base on following document steps.
[https://github.com/Microsoft/nodejstools/wiki/Profiling](https://github.com/Microsoft/nodejstools/wiki/Profiling)

**Comment by billti** [comment]
The profiler is particularly problematic currently in the way it is written, and was written back before Node.js was available as a 64-bit runtime. I have spent considerable time trying to get all the issues fixed with the latest Node.js releases, with little luck. It's going to need a major re-write, and may be removed in the meantime.

If you can profile using an older 32-bit version of Node.js you should have more luck. Sorry I can't offer a better solution currently.

**Comment by paulvanbrenk** [comment]
We're no longer supporting the Node debugger for VS 2017. We may in the future, but closing for now.
