### ISSUE TITLE
Intellisense not working in visual studio 2015 enterprise even after doing a complete reinstall of windows.

### ISSUE THREAD

**Issue by FatalTouch** [Microsoft/nodejstools#1464]
##### Expected Behavior - Intellisense should auto populate methods and parameters in node projects.
![capture](https://cloud.githubusercontent.com/assets/8601052/22367956/3960e6bc-e4aa-11e6-9de2-2d8b3c861bcd.PNG)

##### Actual Behavior - Intellisense doesn't work in nodejs projecs.

- NTVS Version: 1.2.40726.00
- Visual Studio Version: 14.0.25331.01 Update 3
- Node.js Version: v6.9.4

##### Steps to Reproduce
1. Create any new nodejs project using nodejs tools for visual studio.
2. When you try to edit any js file the intellisense doesn't work even if the typings are there. Works normally in visual studio code but doesn't work in VS 2015 Enterprise.

**Comment by UltraNemesis** [comment]
Is this going to be addressed or at least acknowledged? I am facing the same issue. 

Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Node.js Tools   1.2.40726.00
TypeScript   2.1.5.0

**Comment by FatalTouch** [comment]
@UltraNemesis i gave up and started using web storm for my node stuff.

**Comment by billti** [comment]
Hmmmm.... I'm seeing the same thing now. Looks like it's falling back to the "old" JavaScript language service (if you go-to-definition on a built-in type, you can see it takes you to the old .js reference files, not the newer .d.ts files). I'll try and figure out what broke this. As you are using an older build (and I just tried with the very latest), it may be something external to NTVS (i.e. an update in VS itself).

**Comment by billti** [comment]
I think I've tracked it down to this change (https://github.com/Microsoft/nodejstools/pull/1255). If I install the prior commit, things start working again. But that makes no sense if you are definitely on NTVS 1.2, which was prior to this date. Are you sure you didn't install one of the 1.3 pre-releases?

The reason this appears to have slipped though and is only impacting a few users is it looks like if you had an earlier build installed, then those builds set the necessary settings for things to work. Thus customers who upgraded from earlier builds (or developers/tests that move bits forward rather than reinstall) continue to work.

I'll keep looking into the changes around the time this broke and see if I can get this fixed.

**Comment by FatalTouch** [comment]
I am definitely sure that i only had NTVS 1.2 Installed and only when it didn't work i tried one of the pre-release which as you mentioned didn't made any difference.

**Comment by billti** [comment]
I think I've found the root cause, and if you could try a simple change, that would help verify it is the same issue you are seeing before I submit a fix.

Basically we removed the option to select the "Preview" intellisense mode, and made it now the default. However the (TypeScript) engine which provides this new intellisense, still expects to find that option key set, else it bails out.

If you could open `regedt32` and in the registry key `HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\NodejsTools\Options\IntelliSense
` add a string value of `Preview`, hopefully this will get things working.

Let me know if you have any questions about modifying the registry, or if this doesn't resolve the issue for you.

Thanks.

**Comment by FatalTouch** [comment]
@billti Thanks for looking into this.

I made the changes and it still doesn't seem to be working. See these 2 screenshots to see if they can help you find anything.

![node1](https://cloud.githubusercontent.com/assets/8601052/23496803/10931d8e-ff46-11e6-8d3a-82f5e63fada3.PNG)
![node2](https://cloud.githubusercontent.com/assets/8601052/23496802/10911a98-ff46-11e6-9937-df4e7da62d87.PNG)

**Comment by billti** [comment]
Well I can see it is now using the TypeScript engine for the editor instead of the old editor (the tell-tale sign is the 3 drop-down boxes in the Navigation bar, instead of 2).

Interestingly, I can also see in the output window that it says it acquired the typings files for Node (though not express). I assume you are online so it can fetch files from the web?

Which version of TypeScript do you have installed? If you use Help / About, it should show at least version 1.8 (assuming you are on VS2015 Update3). If so, everything should be good.

Could you try just reloading the project (even restarting VS) just to ensure that the downloaded type definitions are picked up. (You may have triggered intellisense before it finished downloading).

Thanks for all your help. Sorry for the pain.

**Comment by FatalTouch** [comment]
The typescript version installed is 2.1.5.0.
Also i restarted the project and it didn't made any difference.
And for some reason it can't find typing for any module i add from npm.

Though i can install them through https://github.com/typings/typings

Anyways i think my dev environment might be too messed up right now because i did try many things to make it work in the first place. I will try later today on a azure VM and will let you know if it works.

**Comment by billti** [comment]
Ugggh, that seems to be it. I just upgraded from the default (1.8) to latest (2.2.1) TypeScript on the box I got working, and now I see the same as you. Guess there's a TypeScript bug as well as a NTVS to fix. Good times.... I'll get on it.

**Comment by billti** [comment]
Alright.... I see the issue now. Unfortunately TypeScript is loading all the definition files into a different project context than the JavaScript files - thus the .js files don't see any of them. This will be pretty easy to figure out, (we made some recent changes here that likely caused this), but the fix probably won't be until the next TypeScript. 

In the meantime, if you drop a file named `tsconfig.json` in the root of the project with the below contents, everything should start working.

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "noEmit": true,
    "allowJs":  true,
    "target": "esnext"
  },
  "exclude": [
    "node_modules"
  ]
}
```

I can explain all the settings if you like, but basically it just says to the TypeScript engine "load all the files under here, including the JavaScript files, as one big project using CommonJS modules". This should do the trick for now.

Really sorry about all this 😞

**Comment by FatalTouch** [comment]
That seems to have done the trick.
Intellisense seems to be working as normal now after adding the tsconfig.json file in the root directory of the proejct.
Will wait patiently for the official release fix in the mean time.

Again thanks for looking into this issue!

**Comment by jamesgmcd** [comment]
asas

**Comment by jamesgmcd** [comment]
NodeJS project output:  **'Could not find Typings package manager tool used for Intellisense**'

I have tried everything and cannot get Visual Studio 2015 Professional Intellisense to work with NodeJS. I have tried on 2 machines at work with no luck. Funny thing is it works at home fine with the Community edition.

Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

LightSwitch for Visual Studio 2015   00325-60004-26858-AA473
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00325-60004-26858-AA473
Microsoft Visual Basic 2015

Visual C# 2015   00325-60004-26858-AA473
Microsoft Visual C# 2015

Visual C++ 2015   00325-60004-26858-AA473
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.18.00214.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Node.js Tools   1.2.40726.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.2.40726.00
Profiling support for Node.js projects.

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   2.2.1.0
TypeScript tools for Visual Studio

**Comment by billti** [comment]
I just put up the latest Dev build for NTVS 1.3 for VS 2015. This (along with the latest TypeScript as mentioned in the release notes) should solve most of the issues in this thread. Let me know if not.

**Comment by jamesgmcd** [comment]
sorry, I tried this but still get the same thing.
'Could not find Typings package manager tool used for IntelliSense'

Node.js Tools   1.3.50306.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.3.50306.00
Profiling support for Node.js projects.

TypeScript   2.2.1.0
TypeScript tools for Visual Studio

**Comment by jamesgmcd** [comment]
What also didn't work with version 1.3 was: New Project -> From existing Node.js code. It just sat in the 'creating Project' without proceeding any further.

Rolled back to 1.2 and worked fine.
