### ISSUE TITLE
Mocha tests should be run from root directory

### ISSUE THREAD

**Issue by Noderino** [Microsoft/nodejstools#1477]
##### Expected Behavior 
In addition to previous issue https://github.com/Microsoft/nodejstools/issues/1476.
If you don't run Mocha from project root Mocha can not read mocha.opts file. Because Mocha tries to find test folder. Also when i use mochawesome reporter it creates "mochawesome-reports" folder in root directory as expected.

##### Actual Behavior 
If you run test from Test Explorer mochawesome creates reports in the same directory with test file.
This is what i got from task manager: "cmd.exe" /S /C pushd <ProjectRoot>\test\benchmarks & ...
It should only push root directory.

- NTVS Version: 1.2.40726
- Visual Studio Version: 2015 Update 3
- Node.js Version: v6.9.5
- Mocha Version: 3.2.0

**Comment by paulvanbrenk** [comment]
Is this still an issue in the 1.3 release? Can you share a small sample project that shows the issue if it does?

Thanks!

**Comment by briman0094** [comment]
I can confirm that this still happens in 1.3.0.7. I am calling a `gulpfile` from a test hook to compile my TypeScript before running tests. When running from my NPM test script, the tests run fine, but when running from the VS2017 Test Explorer using NTVS's Mocha adapter, it complains that it cannot find `gulpfile.js` in the test directory (due to the fact that CWD is in the test directory instead of the project root).

A fix is to add

```
let process = require( "process" );
process.chdir( path.join( __dirname, ".." ) );
```

to the beginning of the hook file (assuming the hook file is in the root of the test directory).

**Comment by paulvanbrenk** [comment]
The behavior with respect to the working dir, is now the same when invoking `mocha` from the command line and through the test explorer.
