### ISSUE TITLE
does not respect ".npmrc"

### ISSUE THREAD

**Issue by mortefos** [Microsoft/nodejstools#1491]
##### Expected Behavior 
packages.json to contain my settings from my .npmrc file

##### Actual Behavior 
packages.json contain none of my settings, and uses the name of my windows user folder as the author

- Visual Studio Version:  Visual Studio Community 2017

##### Steps to Reproduce
1.  Create new nodejs (typescript) project
2.  Open packages.json

**Comment by paulvanbrenk** [comment]
A nodejs project uses a Visual Studio template for the `packages.json` file, the variables in the template are replaced with their values by Visual Studio... since `npm` is not invoked the `.npmrc` file is not used. Changing this behavior would be a significant workitem. closing this as we won't realistic do this in the future.
