### ISSUE TITLE
Mocha unit tests should time out

### ISSUE THREAD

**Issue by danderson00** [Microsoft/nodejstools#154]
Mocha includes a built in test time out of 2 seconds. The integrated test runner should share this behaviour.

**Comment by mousetraps** [comment]
Heh, our comment on this is currently...
```javascript
//set timeout to 10 minutes, because the default of 2 sec might be too short (TODO: make it configurable)
```

I'm not quite sure how we got from 2 seconds to 10 minutes... but yeah, I agree the default should be mocha's default, and we should also make it configurable.

**Comment by lukedgr** [comment]
I am working on a pull request to make running mocha tests more configurable.  It should be ready by EOD today, but if you'd like preview you can see the changes I've made at https://github.com/lukedgr/nodejstools

**Comment by mousetraps** [comment]
Awesome, excited for the PR!

Taking a look at the earlier commits on this... we probably chose 10 minutes instead of 2 seconds is because it *wasn't* configurable, so we had to account for the worst case. I wouldn't mind making the default timeout shorter so long as it's easily configurable. And this only affects running unit tests within visual studio, not the actual code itself, so it's not necessary to optimize for backwards compatibility here.

@yugangw-msft looks like you wrote this code initially - any thoughts on this?

**Comment by yugangw-msft** [comment]
Make it configurable would be great, and yes, "backwards compatibility" is less a concern as long as the accessibility is clear.
The major reason I put in 10 minutes is to take into the account the time break in a debugging session, say, hit BP, thinking, F5 to the next BP, which could last a while, particularly when you debug other people's tests.

**Comment by mousetraps** [comment]
Mocha unit tests now timeout properly more quickly when you are not running in debug mode, and it's available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)
