### ISSUE TITLE
gulp command not found

### ISSUE THREAD

**Issue by lilred** [Microsoft/nodejstools#157]
From the Task Runner Explorer output in the Output window of VS2015:

    Failed to run "[...]\Gulpfile.js"...
    cmd.exe /c gulp --tasks-simple
    'gulp' is not recognized as an internal or external command,
    operable program or batch file.

**Comment by mousetraps** [comment]
Closing this as external. 

Happy to reopen if you think otherwise, by this doesn't look like an NTVS issue, and should probably be filed on the task runner explorer extension instead. That said, without any further context, my best guess is that gulp isn't installed in the correct location (should probably be both global and as dev) or environment variables are not set properly.

**Comment by lilred** [comment]
Thanks for the fast answer! I thought the Task Runner Explorer was part of this project. I'll file against their repo.

**Comment by mousetraps** [comment]
No worries, people-hopping is fun :smiley:. There's so much stuff, and it's hard to tell where it's coming from sometimes.
