### ISSUE TITLE
Please add support for snippets

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/nodejstools#158]
Snippets currently only work in client side Javascript (when the file is marked with Build Action: Content).

It would be great if snippets also worked in NodeJS Javascript files.

**Comment by mousetraps** [comment]
This has been fixed in #339

**Comment by mjbvz** [comment]
Quick update in case anyone runs across this. I removed the snippets features from NTVS 1.3 with #1263 since they already did not work in NTVS 1.2 when using ES6 IntelliSense. Our editor is now powered by TypeScript, and the TypeScript team is adding support for snippets: Microsoft/TypeScript#312 

In VS 2017 ("VS15"), the new TypeScript snippets are now available:

![image](https://cloud.githubusercontent.com/assets/12821956/19535959/c2c3d310-95fe-11e6-95dd-b9fc055d9662.png)

I'll have to check if this was also ported back to TypeScript 2.x for VS2015.
