### ISSUE TITLE
InteliTrace not showing suggestions

### ISSUE THREAD

**Issue by nathan130200** [Microsoft/nodejstools#1588]
##### Actual Behavior 

- NTVS Version:
- Visual Studio Version: 
- Node.js Version: 

##### Steps to Reproduce
1. InteliTrace not working, no auto-complete code or display avaiables requires.

**Comment by nathan130200** [comment]
InteliTrace says that "don't have support for this language." while i create nodejs projects

**Comment by paulvanbrenk** [comment]
I'm not sure what the issue is you are reporting. 

IntelliSense works for me as expected, this is the completion list etc. when editing code. And it is correct that we don't support Intellitrace, which is the tool to do timetravel debugging. 

Can you add a screenshot of the actual issue you're seeing?

Which version of VS are you using?

**Comment by nathan130200** [comment]
I'm using VS2017.

**Comment by paulvanbrenk** [comment]
We currently have no plans to support IntelliTrace.
