### ISSUE TITLE
Web browser launching is problematic

### ISSUE THREAD

**Issue by billti** [Microsoft/nodejstools#1711]
The code at https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Project/NodejsProjectLauncher.cs#L422 launches and loops indefinitely until the expected port is open - which may never happen, so the thread just runs in a loop forever. This should have a timeout, or ideally a way to stop once the process being debugged has exited (as the other launch methods in this file do).

Also, this code should honor the "Launch web browser" checkbox on the project properties. That doesn't seem to do anything in some project types.

**Comment by paulvanbrenk** [comment]
This works for all templates when you use `process.env.PORT` to specify which port node should be listening on for connections.

I added a timeout in the Node 8 case, since we currently don't have a way to get the process id for the Node process the debugger starts.

Do you still expect the browser to start if we can't determine if Node has actually started? If so which URL should we open the browser with?
