### ISSUE TITLE
VS2015 Member not found exception when cancel "add new item"

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#183]
1. In a folder with package.json, try to add a new file also named package.json through the Add New Item dialog
2. When the prompt appears asking whether you want to overwrite the existing file, select no, you don't want to overwrite it.

The following dialog will appear
![image](https://cloud.githubusercontent.com/assets/762848/8026930/cd3953a8-0d40-11e5-9b76-789115034bb6.png)

**Comment by zhengbli** [comment]
I wonder what should be the desired behavior if the user chose not to override:
1. Just cancel and don't add any new file
2. Create a file with a slightly different name, say "package - Copy.json"

Thoughts?

**Comment by zhengbli** [comment]
Ok I found the problem is at the [``GetGuidProperty`` ](https://github.com/Microsoft/nodejstools/blob/master/Common/Product/SharedProject/HierarchyNode.cs#L822) function. When the user click on "no" on the override window, The ``propid`` becomes -2070, which doesn't match any existing guid in ``__VSHPROPID``. Therefore it would always be set to an empty guid, which triggers the "Member not found" error. 

Though I'm not very sure what to do about it at the moment.

**Comment by mjbvz** [comment]
Following the provided steps, I'm no longer able to repo this with NTVS 1.2 Alpha on VS 2015 Update 2. Please reopen if this problem is still happening.

Thanks.
