### ISSUE TITLE
Test discovery is not working when default processor architecture set to x64

### ISSUE THREAD

**Issue by Ruslan-B** [Microsoft/nodejstools#19]
In Visual Studio 2013. (node.js x64) 
Tests cannot be discovered or displayed in grey after this settings is applied:
Test->Test Settings -> Default Processor Architecture -> x64

**Comment by lukedgr** [comment]
I was facing a similar issue, where I had another test adapter that was causing the vstest.discoveryengine.exe to run (instead of vstest.discoveryengine.x86.exe) and this resulted in the tests not being discovered.  However, I found the following work around. 

First, download the source code, and recompile the TestAdapter project with 'Any CPU' as the target platform. Then, replace the test adapter dll in the install directory with the dll that was generated from this compilation and re-open Visual Studio.

**Comment by mousetraps** [comment]
@lukedgr Indeed that works! Just verified we don't have any 32-bit-required dependencies in the project and submitted a PR.

**Comment by mousetraps** [comment]
Fixed in #111

**Comment by mousetraps** [comment]
Available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)

**Comment by toddpi314** [comment]
NTVS 1.0 - Mar 25, 2015 - Where not seeing any tests get picked up, regardless of configuration, on VS 2015 RC.
5-13-2015 Dev Build - Confirmed resolved for all architectures.

Thanks!
Todd
