### ISSUE TITLE
Debug node-webkit/nwjs application

### ISSUE THREAD

**Issue by awn70** [Microsoft/nodejstools#212]
Hi,
is it possible to debug the code running in the node part of a node-webkit (nwjs) application?
(Attach the remote debugger etc.?)
Regards
Andreas

**Comment by mousetraps** [comment]
Haven't personally tried NW.js, but there's no reason it shouldn't work, so let us know if you run into any issues.

 Here's a few resources to help get you started:
* [NW.js debugging docs](https://github.com/nwjs/nw.js/wiki/Debugging-with-devtools) - opening up the port
* [NTVS local attach docs](https://github.com/Microsoft/nodejstools/wiki/Advanced-Debugging#local-attach)
* check out the workaround [here](http://nodejstools.codeplex.com/workitem/1368) re:```#ping=0``` if you run into any issues (planning to document it, but haven't gotten the chance yet)

**Comment by awn70** [comment]
I can see the node process in the "attach to process" window, but when I try to attach Visual studio shows a message box with a timeout error.
This is what I've done:
1) Changed current directory to my nwjs project
2) Started the app with: C:\nwjs-v0.12.2-win-ia32\nw.exe --remote-debugging-port=9222  "."
(tcpview shows nw.exe listening on port 9222)
3) Opened attach to process window in Visual Studio, entered "Transport: Node.js remote debugging", "Qualifier: tcp://localhost:9222/#ping=0", and hit refresh
4) Selected the node.exe entry in the list and hit attach
(Message box appears with something like "attaching not possible, timeout", but tcpview shows established connections to Visual Studio.)

**Comment by mjbvz** [comment]
I believe that Nw.js is using the Chrome debug protocol, not the v8/Node debug protocol that we currently support, and that's why attachment fails. 

With the Chrome debug protocol having [now landed in Node proper](https://github.com/nodejs/node/pull/6792), and the V8 debug protocol deprecated, we do plan on adding support for the Chrome debug protocol as part of a larger debugging effort sometime in the future.
