### ISSUE TITLE
ECMA 6 Support / Parsing Override

### ISSUE THREAD

**Issue by atom0s** [Microsoft/nodejstools#265]
This would be more of a feature request, or "does this exist already" type issue.

I am working on a project that makes use of ECMA via the --harmony command line option. However, the parser in Visual Studio does not see the usage of ECMA things as valid. Such as fat arrows and similar. 
http://i.imgur.com/wxsDPD5.png

Along with that multiple usage lands up causing VS to nearly stop parsing a file that makes use of ECMA 6 features heavily causing a 'Too many errors' report saying the file is probably not a Javascript file.

Just wondering if there are plans to override the parser to allow ECMA 6 features, or if this feature already exists. 

I'm using Visual Studio 2013 Update 4.

**Comment by interdrift** [comment]
ES6 Usage in the Editor

Some ES6 usage will cause IntelliSense to fail in a broader sense - this includes things that involve new syntax. For example arrow functions will give syntax errors, but new methods on array just won’t show up in IntelliSense and won’t be analyzed. New scoping rules would probably just give wonky IntelliSense. So really only things that involve new syntax would show up as being broken (display errors and otherwise hurt IntelliSense).

Until we implement those features, you can work around any IntelliSense issues by ignoring directories for analysis


Taken from wiki : 
https://github.com/Microsoft/nodejstools/wiki/io.js-and-ES6-support

**Comment by atom0s** [comment]
Ah totally overlooked the wiki on here, sorry about that. Answers this question / feature request then. 
Thanks for the link.

**Comment by sjmueller** [comment]
Can the wiki be updated to discuss debugging limitations with iojs as well?  Also would be great to talk about transpilation with [babeljs](https://babeljs.io/docs/setup/#babel_register`) using `require("babel/register");` 

Visual Studio has the opportunity to provide an amazing node debugging experience with modern javascript, especially since nobody else is even close to doing it well.
