### ISSUE TITLE
Disable nodejstools Parser

### ISSUE THREAD

**Issue by atom0s** [Microsoft/nodejstools#278]
In ReSharpers lastest releases they support ECMA 6 and it works quite well. Same with Visual Studio 2015's latest updates. However, using NodeJS Tools seems to break any usage of their parsing and causes ECMA6 code to show as invalid/errors.

I do not see any option to completely disable NodeJS' parser so that I can just make use of the stock JavaScript parser or allow ReSharper to handle parsing and validating the JavaScript. 

Is there a way to disable NodeJS Tools parser to allow other parsers to do the work for now until ECMA6 is fully supported?

**Comment by mousetraps** [comment]
Yes, if you mark your file as "content" instead of compile, it will open in the default VS editor rather than the Node.js editor, and also won't be analyzed. Be forewarned, though, we highly advise against using ReSharper alongside NTVS (or any Node project, really) due to potential perf issues (unless they've changed anything recently... their engine provides completions by executing your code rather than using static analysis): see this issue for more info https://nodejstools.codeplex.com/workitem/1584

**Comment by mousetraps** [comment]
That said, if you already have ReSharper enabled, and are happy with the perf, then it shouldn't be a concern (this is one of those issues that depends on the project itself.)

**Comment by atom0s** [comment]
Is there an easy way to make all files content to ease this task?

**Comment by mousetraps** [comment]
We'll have a build out soon that adds that feature (right click on a folder to mark all files as content), so feel free to go ahead and build NTVS from source.

**Comment by mousetraps** [comment]
Otherwise, you could close your project and do a search & replace through your .njsproj file.

**Comment by atom0s** [comment]
Alright. Sounds like the next build will be the best option. 

As a request could there be a new option added in node.js' options to not use the node.js editor instead of using the content workaround?

**Comment by billti** [comment]
We're working on features to address this, but won't be at 'release' quality for a release or two.

**Comment by mousetraps** [comment]
This was addressed with #243 as well as the new ES6 IntelliSense Preview
