### ISSUE TITLE
Code improperly indents after if block inside inline callback function

### ISSUE THREAD

**Issue by spazmodius** [Microsoft/nodejstools#3]
I cannot find a combination of settings that produce the right indentation behavior.  This is what I get for Smart Indenting:

If I'm here:
![image](https://cloud.githubusercontent.com/assets/259818/6888019/777e3430-d63e-11e4-89c0-5f749233417a.png)
and hit Enter, I wind up here:
![image](https://cloud.githubusercontent.com/assets/259818/6888024/89c5164a-d63e-11e4-9305-a2c1882fbe4b.png)
Notice also that the line I left became _unindented_.

**Comment by mousetraps** [comment]
Hmm, looks like a bug, but I can't seem to reproduce that issue with the code you provided. If you press Ctrl+K, Ctrl+D, does it reformat things properly? 

Also I notice that your function block is indented. What is the parent declaration? Is it a function?

**Comment by spazmodius** [comment]
Yes, Ctrl+K,D works.  Curiously, it also pads blank lines with tabs.

Yes, the function is nested a couple levels deep.  Here's a simple repro https://gist.github.com/spazmodius/2da9b1e242351378b6f1

Notice, if you go to the end of any line in `onResponse()` and hit `enter`, you will be far too indented.

Note: The unindenting of the one line seems to be because the whole block in my project was_already_ indented one level further than it should have been (an editing error).  So the line was moved to it's _ideal_ indentation, instead of relative to it's surrounding code.  It's debatable whether that's a problem, so let's ignore it for now.

**Comment by mousetraps** [comment]
Aha, I can repro both issues now. Yeah, there are a few indent/dedent oddities that need to be ironed out. The following issues may be related (all involve 3-tab differences, assuming 1 tab = 4 spaces):
* https://nodejstools.codeplex.com/workitem/1654
* https://nodejstools.codeplex.com/workitem/1830

We chose not to fix it for 1.0 because it might be too destabilizing - formatting changes have a habit of having unforeseen side effects. We should revisit this issue now that we've shipped, though.
