### ISSUE TITLE
Run with build errors

### ISSUE THREAD

**Issue by anjdreas** [Microsoft/nodejstools#312]
One thing I found annoying is that the TypeScript NodeJS project refuses to run if there are TypeScript build errors. I understand that build errors are there to help you, while the JS is normally still output. This means I expected to be able to run despite build errors, but instead it just shows me the error list window on F5. I don't see any options in the project to enable the behavior I want.

I've fixed all build errors to be able to run, but it would be very convenient to run code that you know works, but simply suffers from TypeScript related errors.

**Comment by mousetraps** [comment]
Unfortunately we don't have much control over this in Node Tools - this experience is owned by the typescript team, so I recommend filing an issue there. 
https://github.com/microsoft/typescript

**Comment by NoelAbrahams** [comment]
Can't really say much, because we don't try anything with a broken TypeScript build.

I think there needs to be at least one successful build. I get the following:

![image](https://cloud.githubusercontent.com/assets/1106823/9060057/ffed9f40-3aa7-11e5-889e-d6a497a4783a.png)

![image](https://cloud.githubusercontent.com/assets/1106823/9060060/10db05ae-3aa8-11e5-80e7-c29584dc1e9f.png)

**Comment by anjdreas** [comment]
Opened issue over at TypeScript instead.
