### ISSUE TITLE
Weak intellisense within functions

### ISSUE THREAD

**Issue by mavericken** [Microsoft/nodejstools#313]
I noticed some trouble with intellisense inside my functions today:
![image](https://cloud.githubusercontent.com/assets/7833752/8879669/e3e4e88a-3200-11e5-8e86-3719b3003047.png)

![image](https://cloud.githubusercontent.com/assets/7833752/8879687/f8f2a12c-3200-11e5-8a06-262a0f588aaa.png)

Text version for convenience:

    {
        // NOT in a function
        var cat;
        if (true) {
            cat = { sound: "meow" };
        }
        var it = cat;
    }

    function animalStuff() {
        // in a function
        var cat;
        if (true) {
            cat = { sound: "meow" };
        }
        var it = cat;
    }

Version information:
Microsoft Visual Studio Community 2015
Version 14.0.23107.0 D14REL
Node.js Tools   1.1.30716.01

**Comment by mjbvz** [comment]
This got worse with ES6 Intellisense preview in NTVS 1.2 Alpha. Now cat is displayed as an `any` type in both cases.

**Comment by mjbvz** [comment]
Marking this as external since in NTVS 1.2 Beta, ES6 IntelliSense is backed by Typescript / Salsa. Fixing this would likely require work on their side.

**Comment by mjbvz** [comment]
Fixed by TypeScript in latest VS2017 builds:

![image](https://cloud.githubusercontent.com/assets/12821956/19579871/a5ceadfa-96d7-11e6-9ee2-f5df51d97545.png)

![image](https://cloud.githubusercontent.com/assets/12821956/19579884/b28e2494-96d7-11e6-8f2c-3c308f61ef22.png)

I believe TypeSccript 2.0 may also have improved this in VS2015.
