### ISSUE TITLE
Domain IntelliSense

### ISSUE THREAD

**Issue by AeonRush** [Microsoft/nodejstools#318]
```javascript
var domain = require("domain");
var d = domain.createDomain();
```
And IntelliSense doesn't work. Doesn't show me variants. But "domain" is standard module in Node.js

**Comment by mavericken** [comment]
I think it would be useful if we had some kind of intellisense.js file feature that we could repair intellisense on these things.  Maybe one already exists and I just don't know about it.  Is there a document somewhere that describes all the intellisense features of the new provider?

**Comment by mousetraps** [comment]
IntelliSense for standard modules is based on parsing Node's documentation. 
https://nodejs.org/api/all.json

We have a copy of it available in the following location if you want to edit it in any way, but it won't be preserved when upgrading NTVS. 
"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Microsoft\Node.js Tools for Visual Studio\1.1\all.json"

In this case, createDomain is not documented so we won't provide completions. As for further IntelliSense (if you were to use, say create) for some reason we're not parsing the signature to flow through the return type of the method for built-in modules. 

@mavericken can you be more specific about your mental model re: IntelliSense and/or what you might want to edit? IntelliSense is pretty complicated and there isn't a particularly user-friendly way of wading through it all, so unfortunately the best documentation at the moment is the code itself.
https://github.com/Microsoft/nodejstools/tree/master/Nodejs/Product/Analysis

**Comment by mavericken** [comment]
I was thinking about the IntelliSense extension feature shown in this article: https://msdn.microsoft.com/en-us/library/vstudio/hh874692.aspx
In particular, I was looking at how you can adjust intellisense of any existing Javascript file by adding an additional Javascript file and not have to change the original.  Sounds like such a feature isn't necessary for this case, though.

**Comment by mousetraps** [comment]
@mavericken ahh, gotcha. We used to extend the JavaScript language service (which is what you linked to) for completions, but no longer do because executes code in order to provide IntelliSense, which was causing major perf issues with the large Node projects people were working with. Now we statically analyze your Node code, which generally doesn't bring VS to a crawl (yay!), but the downside of this is that it involves a bunch of craziness with abstract syntax trees, visitor patterns, many types and definitions stored in memory, all updating as functions get used in different ways or new code is written, various optimizations, etc... all of which tend to make it really difficult to actually follow and conceptualize what's going on.

That said, we *do* want to find better ways to communicate and make it easier to understand to grasp because unless you just throw up an identifiers list, IntelliSense becomes a conceptual black box. And this is all well and good until the completion list doesn't match up with user expectations... I think we've done a good job making the analysis engine really smart, but now we need to focus on making it more predictable (from a user-perspective) so that the gap between user-expectation and reality narrows. And then we can focus on extensibility :smiley:

**Comment by AeonRush** [comment]
In RC 2.1 all works

**Comment by mousetraps** [comment]
@AeonRush what works, specifically? Still getting unknown type on my end
