### ISSUE TITLE
Add telemetry to allow us to detect ppl/scenarios affected by inconsistent debug experiences

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#332]
Debugging is one of our most important experiences, and there are instances where it's not working for some subset of users in a way that we can't quite reproduce.

Adding telemetry will enable us to understand how widespread problems may be and how well each of our fixes are addressing the issue so we can be more confident in the quality of the product we put out.

We can detect this by checking whether debugging was started, and hit a certain point during attach-to-process. And actually... better yet... if we have a good way of detecting the issue, we can offer the user steps to get past it (maybe print a message in the debug output window directing them to github).

**Comment by mjbvz** [comment]
From the bugs were seeing now, there does not seem to be a common pattern of debugger issues and I'm not sure we would be able to identify many of them (such as incorrect source mapping). We've added additional diagnostics points for some cases but actually determining when the debugger is in a bad state is very difficult because of our interaction with the node debugger.

In the past, having people report debugger issues and tyring to get a local repo has been our best bet in actually finding and fixing problems with the debugger. The additional project characteristics points we added may help with this initial investigation as well.
