### ISSUE TITLE
Test Explorer view is messed up in VS 2015

### ISSUE THREAD

**Issue by dmitrofanov** [Microsoft/nodejstools#334]
Not sure if this issue should be addressed to the NodeJS team or not ... The Test Explorer view in VS 2015 is messed up when using mocha.

If you have nested describe() then only top level is shown and the rest gets ignored, which makes it nearly impossible to test in VS in large projects. 

For the example depicted below I was expecting to see the following in Test Explorer: 

spread.dal.mongo
--> index #get() should return an object of DataProvider type

Instead I only see this 

spread.dal.mongo
--> should return an object of DataProvider type

This is only an issue in VS 2015, VS 2013 seems to work fine.

![test_code](https://cloud.githubusercontent.com/assets/8118463/8956599/888d9608-35c5-11e5-8ee6-fabdffa97aed.PNG)

![test_explorer](https://cloud.githubusercontent.com/assets/8118463/8956600/8d9fb374-35c5-11e5-920f-1b742a30823d.PNG)

**Comment by dmitrofanov** [comment]
Anyone at all? With the issue described it is very hard to use VS tests in large scale projects ...

**Comment by dmitrofanov** [comment]
I reckon we should probably wait until big bugs are actually squashed in VS2015.

**Comment by mousetraps** [comment]
Thx for reporting this - agreed it's annoying and we can look into it for our next release. This is probably related to #79 (VS changed their unit testing infrastructure between VS2013 and 2015).

Also it's your call, but we would really really appreciate not waiting if you're running into issues because the only reason this wasn't fixed for RC was because we didn't know about it. We have a small team, and our test coverage isn't perfect, so every bit helps :smiley:

**Comment by mousetraps** [comment]
Also quick question - with VS2013 are you running the same version of NTVS? 1.1 RC?

Because I just tried 1.1 RC with VS2013 on my machine and it also doesn't work, so this does not appear to be a VS 2015 issue, but rather a regression caused by some of the fixes we made to the test explorer integration.

**Comment by dmitrofanov** [comment]
Thank you for getting back to me, We'll wait patiently until it is fixed. :-)
You are correct about versions. My VS2013, which has Test Explorer working as expected, has Microsoft.NodejsTools, Version=1.0.2013.0, FileVersion=1.0.30324.01, whereas my VS 2015, where Test Explorer has the above mentioned issue, has Microsoft.NodejsTools, Version=1.0.2015.0,  FileVersion=1.1.30716.01. So it is not VS 2015 problem indeed as I stated earlier!

**Comment by mousetraps** [comment]
Hey I just looked into this, and turns out it was a super simple fix that you can make on your end w/o waiting for a new build - just edit your mocha.js file as follows: https://github.com/Microsoft/nodejstools/pull/349/files

It should be available in:
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Node.js Tools for Visual Studio\1.1\TestFrameworks\Mocha\mocha.js"

Sorry about that - should have caught this issue during code review.

**Comment by mousetraps** [comment]
Fix available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)

**Comment by Laro88** [comment]
I was hoping this to be the solution for missing tests in VS2013 as well, however it was not.
The path is in my case:
C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Microsoft\Node.js Tools for Visual Studio\1.0\TestFrameworks\Mocha
It seems like I am "loosing" tests that newer reappear when fixed. The "loosing" seems to be related to compile errors, compile error -> test dropped from list.
mocha test works without flaws.

There seems to be something fishy going on :-)
