### ISSUE TITLE
NRE on loading project

### ISSUE THREAD

**Issue by generateui** [Microsoft/nodejstools#337]
Output window showing output of Solution displays:

    {myFile}.njsproj : error  : Object reference not set to an instance of an object.

Where can I best get log info causing this error to aid in this issue?

**Comment by mousetraps** [comment]
Thx for reporting this. 

The quickest way to get to the bottom of this issue is by downloading the src and running under the debugger. There is no user-facing logging available for this feature.
https://github.com/Microsoft/nodejstools/wiki/Build-Instructions

And if it's possible, it would be helpful if you could send us your project (or at the very least your project file) so we can try to get to the bottom of it. 

As far as workarounds go, you can using the "new project from existing code" template to create a new project file and see if that helps.

**Comment by mousetraps** [comment]
Hey, thx for reporting - the fix should be available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)
