### ISSUE TITLE
Guidance for unit test execution - How to properly set process.env.NODE_ENV=somethingsensible

### ISSUE THREAD

**Issue by Laro88** [Microsoft/nodejstools#363]
What is the appropriate way to set NODE_ENV for unit testing?
I am asking because I have a testconfig.js that sets up stuff like chai and also the NODE_ENV variable, and I can't get it to integrate nicely into VS2013. Using mocha --require is fine from the shell, but the VS2013 test and test debugging seem to require a different mechanism for setting up.

Is there some way to use the .testrunconfig og .testconfig files for setting up the testing, and if so then could I have a sample.

**Comment by mjbvz** [comment]
If I'm understanding you correctly, I think this is the expected behavior. The test runner runs tests in isolation, so, to set something like `NODE_ENV`, you would have to have to use `before` or `beforeEach` https://mochajs.org/#hooks . You should be able to hook into one of those to setup whatever environment you need before executing the actual test.
