### ISSUE TITLE
Not hitting breakpoints in TypeScript with --outDir option set

### ISSUE THREAD

**Issue by yortus** [Microsoft/nodejstools#380]
I have several TypeScript projects where build outputs are placed in `/built` and their sourcemaps point back to the typescript sources in `/src` (ie making use of `tsc --outDir`).

I've updated to VS2015 and the latest (8-4-2015) dev build of NTVS. Now breakpoints set in the `.ts` source files are not hit.

I had a flawless debugging experience with this same setup with VS2013.4 and NTVS1.0 (unless I'm going crazy - I uninstalled VS2013 before installing VS2015 so its hard to check).

Even though breakpoints in `.ts` files are no longer working, the following _do_ work:
- if a breakpoint is set in a `.js` file anywhere in the `/built` directory, the debugger breaks on the equivalent line in the corresponding `.ts` file in `/src`. 
- If a `debugger;` statement is placed in a `.ts` file anywhere in `/src`, the debugger _does_ break on that line in the `.ts` file.

@mousetraps I noticed you [commented](https://github.com/Microsoft/nodejstools/issues/104#issuecomment-99962084) on something similar a few months back on a another issue (#104). Is this possibly the same problem you were talking about? I'm happy to put together something to repro this if needed. NTVS is awesome BTW! I couldn't count the hours the debugger has saved me.

**Comment by yortus** [comment]
BTW these projects now use `tsconfig` files for their builds. Is that perhaps why NTVS doesn't see the source files? I seem to remember when `--outDir` support was first aded to NTVS, it made use of a build output setting in the `.njsproj` file, which is no longer set for these projects.

Having said that, I've just tried a few different settings in the `.njsproj` files but still can't get it to hit the `.ts` breakpoints.

**Comment by billti** [comment]
Thanks for the report. The source map code hasn't changed much other than one bug fix. We'll take a look into this and make sure it hasn't regressed something.

**Comment by ahmad-farid** [comment]
@yortus Would you be able to provide one of the projects you're encountering this issue with? Thanks!

**Comment by yortus** [comment]
@ahmad-farid I've made a project to repro this. You can find it [here](https://github.com/yortus/ntvs-outdir-repro).

I've put the steps to reproduce in the [README](https://github.com/yortus/ntvs-outdir-repro/blob/master/README.md). On my machine, following the steps to reproduce has exactly the results described there.

**Comment by rkavalap** [comment]
@yortus  have you tried setting the breakpoint on the compiled javascript file instead of the typescript file. I have a similar setup, I compile as a gulp task. The breakpoint only gets hit when set on the compiled javascript file and chains back to the typescript file.. i.e set the breakpoint on the compiled javascript source and the debugger stops on the same line in the typescript file. 
When set on the actual typescript source it does not get hit.  Not sure what the behavior should be here. ?

**Comment by yortus** [comment]
@rkavalap yes that's the behaviour I described in the issue. Quoting myself:

> if a breakpoint is set in a .js file anywhere in the /built directory, the debugger breaks on the equivalent line in the corresponding .ts file in /src.

**Comment by chrisweb** [comment]
I can confirm this issue, I use outDir too and I also put the source files into a seperate folder, I use tsconfig too

visual studio: 14.0.25431.01 Update 3 
nodejs tools: NTVS.Dev.2016-11-02.VS.2015.msi
nodejs: v7.2.0

**Comment by jshwei** [comment]
I did some search, and it looks like the problem is at [`SourceMapper.cs#L219`](https://github.com/Microsoft/nodejstools/blob/bab879e0913fab73da30020400b1f9dea22dacc9/Nodejs/Product/Nodejs/SourceMapping/SourceMapper.cs#L219). Where if I set the breakpoint on the typescript, when it searches for the javascript and javascript map file, it only searches the typescript directory

**Comment by paulvanbrenk** [comment]
This works as expected for the Node 8+ debugger.
