### ISSUE TITLE
Hang opening a solution the 2nd time

### ISSUE THREAD

**Issue by TomBecker-BD** [Microsoft/nodejstools#429]
I installed NTVS 1.1 RC2 VS 2013. When I tried to open a solution the 2nd time, VS would hang. Solution Explorer would show (Loading...). Had to kill VS in Task Manager. Workaround was deleting the .suo file. 

I tried removing VS extensions but that didn't help. There could be a max_path issue because I'm using grunt-contrib-uglify and grunt-jsdoc which have deeply nested node_modules dependencies. However, I didn't get any error messages. Whatever the problem is, there should be some indication and it should not prevent opening the solution. 

I went back to NTVS 1.1 RC VS 2013 and the problem went away.

**Comment by mousetraps** [comment]
Hmm, that's odd. We don't do anything with NTVS that should involve the .suo file (in particular we don't implement `IVsPersistSolutionOpts`)
https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivspersistsolutionopts.loaduseroptions.aspx

Unfortunately I can't reproduce this, so we'll need some additional info to help narrow it down. So you deleted the .suo file, and then it got recreated in a similarly corrupt manner? Does the issue occur with every project type? Do you happen to have a project that it reproduces with that you might be able to share? Does it hang the first time you open the project?

Could you try installing the [latest dev build](https://github.com/Microsoft/nodejstools/releases)? Does the interactive window work before you open a project? (Tools > Node.js Tools > Interactive Window)

Thanks in advance for the help!

**Comment by TomBecker-BD** [comment]
Good question! The interactive window does not work before I open a project. I get an error dialog
> "Sequence contains no elements". 

ActivityLog.xml contains some warnings and errors: 
> 10 Warning PkgDef configuration error. ApplicationExtensionsFolder omitted from PkgDefSearchPath   VisualStudio 2015/10/12
> ...
> 631 ERROR Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
>           C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 12.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\NODE.JS TOOLS FOR VISUAL STUDIO\1.1\Microsoft.NodejsTools.dll   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2015/10/12 17:54:59.658 
> 632 ERROR Could not load file or assembly 'Microsoft.NodejsTools.InteractiveWindow, Version=1.0.2013.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
>           C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 12.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\NODE.JS TOOLS FOR VISUAL STUDIO\1.1\Microsoft.NodejsTools.dll 
> (repeated another 7 times)

Microsoft.NodejsTools.dll does exist at that location. I don't know why it couldn't be found.

**Comment by mousetraps** [comment]
That's my litmus test for MEF composition issues :smiley:.

First make sure you've installed NTVS 1.1 RC 2.1 or higher, as 1.1 RC2 had some MEF issues in VS 2013.
https://github.com/Microsoft/nodejstools/releases

And if that doesn't work, try forcing the MEF extension cache to be rebuilt (this should happen automatically when new extensions are installed, but sometimes it fails):

1. Delete the contents of the folder at `%LOCALAPPDATA%\Microsoft\VisualStudio\14.0\ComponentModelCache`
Run `DevEnv.exe /setup` (this is under `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE`, but should be on your `PATH`  if you open a Developer Command Prompt).
2. Next time you launch VS it will take a while to rebuild (which may be part of the delay above), but should resolve any MEF errors.

Hopefully one of those two options will work, otherwise we can start digging into the error log files (which are also in the ComponentModelCache folder.)

**Comment by TomBecker-BD** [comment]
I tried NTVS.Dev.2015-09-17.VS.2013.msi and it worked no problem. I also tried NTVS 1.1 RC2.1 VS 2013.msi and I was able to open the interactive window, and also to open and close the solution. When I closed the solution I got an "Unexpected error occurred" dialog. But it left VS in a usable state, so I think the problem has been fixed.
