### ISSUE TITLE
Make .npm Interactive Window command work for all project types

### ISSUE THREAD

**Issue by warrendodsworth** [Microsoft/nodejstools#480]
In a normal MVC project VS2013.
I've configured everything and am able to use npm in the command prompt in the solution directory.
NTVS allows global installs using .npm install -g

**But I cant seem to find a way to tell it which project to point at**

It says "If solution contains multiple projects, specify target project using .npm [ProjectName or ProjectDir] <npm arguments>"

I've tried the project name and the full uri to the project directory on my local machine.

**Comment by mousetraps** [comment]
An MVC project isn't a valid Node.js project type, but we'd be happy to accept a PR to change this behavior to work more generally. 
https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Repl/NpmReplCommand.cs#L107

**Comment by mousetraps** [comment]
Also did you include the brackets with the command? The syntax isn't entirely clear.

**Comment by warrendodsworth** [comment]
Hi, thank you for your reply. 

I have installed Nodejs and Git which is a Bower dependency.
In the MVC project after creating package.json, with the help of a VS extension called Package Intellisense I was able to get node_modules created.

I could also do this by using the command line in the solution folder and running "npm install"
Which works fine, got bower and gulp setup using the command line.

I would like to be able to use these npm commands from NTVS.
When I run npm install I see this
> Please specify a valid Node.js project or project directory in solution. If solution contains multiple projects, specify target project using .npm [ProjectName or ProjectDir] <npm arguments>

So there's probably a way to set the project and let npm know which one were referring to.

I ran `.npm [MvcProjectName]` and got back, this did not however set the project and I kept getting the error message on the next command.

> Specify configs in the ini-formatted file:
    C:\Users\Warren\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config
npm@2.14.2 C:\Program Files\nodejs\node_modules\npm
[JobAdder.Web.Public] successfully completed


I also ran `.npm [JobAdder.Web.Public] install bower` to no avail.

**Comment by mousetraps** [comment]
If JobAdder.Web.Public is a Node.js project type in your solution, then it should work. If not, it won't work using the [ProjectName] specification. 

Alternatively in order to use a [ProjectDir] specification - where you copied the full path, you'll need a package.json file there for it to be considered a valid Node.js project.

As I mentioned above, feel free to submit a PR if you'd like to change the behavior to be more inclusive. 

We have not implemented switching project path context yet, but that would require far more design work. We actually implemented it once, but reverted because we we didn't want to destabilize the product at that time and hadn't thought through the user experience and edge cases well enough.

**Comment by warrendodsworth** [comment]
Thanks for the reply and explanation. 
As soon as I can find the time I'll give it a look. 
In the meantime I found a VS plugin Open Command Line - which opens Powershell etc using Alt + Space. So that works for now.

**Comment by mousetraps** [comment]
@madskristensen another reason consolidating External Web Tools + Node.js Tools settings would be good - lets us light up features like the Interactive Window in other project types. Additionally, exposing an interface to grab the proper executable path would be helpful.

**Comment by kimballjohnson** [comment]
I got this meessage: "Please specify a valid Node.js project or project directory. If your solution contains multiple projects, specify a target project using .npm [ProjectName or ProjectDir] <npm arguments> For example: .npm [MyApp] list" And then I've been reading the discussions about this text instruction and I don't understand what you don't understand. The issue is not about the text of the message, its about the confusing situation that the confusing message is trying to instruct you how to solve. The problem is, however, that the problem is insoluable from the user's perspective. The actual problem that necessitates the message is: "You are not calling the interactive window from within a node.js project." That problem is caused by the fact that NodeJs tools enables the user to open the interactive window in a project that is not a nodejs project. Which means that NodeJs tools cannot itself identify what is a nodejs project and what is not a nodejs project. It should do nothing if it isn't in a nodejs project!!! and it should be able to tell the user exactly what it means when it refers to what it thinks is a nodejs project. Therefore, enabling nodejs tools to 'do its thing' in just any project may seem like a solution, but that makes nodejs-tools into a 'nodejs look-alike tool for just any old project type'. Is that really what you want to do with the tool? And then you start building in features to make gulp do stuff that nuget does, and that msbuild does, and then... and then... Instead! please re-focus on bringing actual nodejs tool features into a verifiable VISUWALL STYEWDEO native terminal window like you find in WebStorm and that gaggle of other editors that are just jsFiddle in a packaged browser. Like... hey! How about a command line that can parse 'en' 'pee' 'em' without a leading period! Even the terminal in Webstorm can use Powershell as the command line without requiring a leading period! Or how about parsing hyphen g before or after the name of the lib to install! Please stick to the plan and follow the way. THat's how whoever did it got to nodejs... by sticking with Kernigan and Ritchie up until this very day when a forty year old command line is still ruling half the world or more. Come on people! This isn't helping! Woudl you use something called 'NodeJS Toyes?'
