### ISSUE TITLE
New Announcements issue

### ISSUE THREAD

**Issue by regisbsb** [Microsoft/nodejstools#490]
Now that we moved from Codeplex could we create a announcements thread (locked of course) that people can subscribe like the other MS projects?

**Comment by mousetraps** [comment]
Mind giving an example?

**Comment by mousetraps** [comment]
Oh, you mean a GH thread? Yeah we could do something like that.

**Comment by regisbsb** [comment]
Cool cheers!

**Comment by code-Review-2015** [comment]
how about a gitters chat?  https://gitter.im/Microsoft/NTVS
https://github.com/Microsoft/PTVS

**Comment by regisbsb** [comment]
not a bad idea

**Comment by mousetraps** [comment]
Tada! https://gitter.im/Microsoft/nodejstools

**Comment by SteveALee** [comment]
Cool - though don't forget decisions should be archived in public. Is gitter archived and easy to search? I guess important stuff tracked in issues anyway?

**Comment by regisbsb** [comment]
@SteveALee it is. and it can hyperlink the issues in github. have a go. you will like it.

**Comment by SteveALee** [comment]
Indeed it is good and I see you can link out for comment to issue. But there seems to be no way to get a permalink to a comment so can ref it from an issue or otherwise.

Anyway they say unlimited history for open threads which is what you need to ensure project memory is never lost (an data export would be even better)
