### ISSUE TITLE
Startup file not preserved after being moved to another directory

### ISSUE THREAD

**Issue by Akudrevatykh** [Microsoft/nodejstools#5]
New Blank Node.js Console Application works fine.

However if I move app.js into a 'src' folder and update package.json `"main": "./src/app.js"` then I can no longer start the app:
`No startup file is defined for the startup project`

**Comment by mousetraps** [comment]
Yeah, we should fix the whole not-preserving-the-startup-file-value if you move it issue.

As far as what you can do now... if you right click "app.js", you'll be able to set it as a startup file. The reason we do this instead of reading the value from package.json is to enable people to easily switch the file they are starting up with. We should definitely edit this message to be more useful, though. (see #6)

I also just filed a feature request to consider choosing the file defined in package.json as the default startup file (see #7).
