### ISSUE TITLE
Streamline NTVS build instructions

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#53]
There are a few things that could be automated using a powershell script.
http://nodejstools.codeplex.com/wikipage?title=Build%20Instructions%20for%20NTVS

**Comment by mjbvz** [comment]
Updated location: https://github.com/Microsoft/nodejstools/wiki/Build-Instructions

Still could be improved somewhat since a few manual step are required on initial setup (`Microsoft.NodejsTools.targets ` copying, `EnableSkipVerification.reg`, ...) so we may want to create a `setup.ps1` script or something similar.
