### ISSUE TITLE
NTVS can not load installed global packages

### ISSUE THREAD

**Issue by iccfish** [Microsoft/nodejstools#537]
Using Node 4.2.1 x64 & NTVS dev build(10-14), I can't get NTVS to load installed global packages, as there is no intellisense for `require` and treat result by `require()` as unknown type.

Run `npm list -g` can list all global packages.
I can't figure out what's the problem currently.

![ntvs_3](https://cloud.githubusercontent.com/assets/1091653/10495391/34eb0cf4-72ee-11e5-95e9-05a15385f772.png)

![ntvs_4](https://cloud.githubusercontent.com/assets/1091653/10495396/389fd848-72ee-11e5-9895-abb1dfc4c6ce.png)

**Comment by mousetraps** [comment]
You'll have to install it locally in order to get IntelliSense on your project. This is because we do cross module analysis, and things would get really complicated really fast if we had to deal with global packages.

**Comment by iccfish** [comment]
Thanks for explanation. However, it makes global packages no sense and drops down convenience a little bit.

**Comment by mousetraps** [comment]
Thanks for the feedback. Quick Q so I can understand... What reasons are there to use require on a global package? Node itself won't even execute that because it will fail to resolve the module unless you are doing some linking somewhere or are setting NODE_PATH to globally installed packages. 

In general, people use global npm pkgs for for cli utils and locally installed pkgs for things related to the app they're writing.

**Comment by jimior2** [comment]
Otherwise, if you using VS2015 then you could goto Tools > Options > Projects and Solutions > External Web Tools to setting Locations of external tools, and move PATH up, then the NTVS tools default node will using global package.

![image](https://cloud.githubusercontent.com/assets/654999/10765665/cd5436e4-7d0e-11e5-972d-c17cdd3267e2.png)
