### ISSUE TITLE
How do I run my "Basic Azure Node.js Express 4 Application" template project from command line

### ISSUE THREAD

**Issue by eljamaki01** [Microsoft/nodejstools#563]
For some of the Visual Studio created node projects, I can go to that directly and run "node app.js" and it works. However, this does not work with the Express 4 Azure template.

if I run "node bin\www" it does nothing.

**Comment by mousetraps** [comment]
That should work fine. One thing to note about the express 4 template is that it doesn't print out the "Express server listening on port XXXX" line, but you should be able to navigate to the port (I believe the default would be localhost:3000 in the command line since it's not picking up process.env.PORT from the VS config. otherwise it's typically localhost:1337)
