### ISSUE TITLE
Not seeing the option to exclude folder from intellisense for browser code

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#616]
This seems to happen whatever intellisense option I choose. Once when I created a folder called public it automatically said (browser) at the end of the name.

![image](https://cloud.githubusercontent.com/assets/618922/11441558/28b03ab6-9505-11e5-874b-16cc9bbf1642.png)

**Comment by mousetraps** [comment]
That's because there aren't any javascript files in that folder. The property is not actually saved on folders - it's inferred from files.

**Comment by SteveALee** [comment]
Haha. That explains why I saw it before as I had a JS file there at that time!

**Comment by SteveALee** [comment]
However, my html file hads inline JS. So there :)

**Comment by mousetraps** [comment]
lol... but you bring up a good point - it's not a bad idea to infer from html there... :smiley:

That said, we probably won't do anything about it any time soon because I anticipate a lot of project system changes going forward as we migrate to a file / folder-based system (#262) and also as the combined analysis engine comes together.
