### ISSUE TITLE
What versions of Node.js can be used?

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/nodejstools#62]
Are there any limitations on which version of Node.js can be used with NTVS? The only mention that I can find of a specific version of Node.js is on the [download page](https://nodejstools.codeplex.com/releases/view/612573) where it says "*Node.js versions 0.10.34 and 0.10.35 break debugger functionality. The issue has been fixed in later versions of Node.js.*"

I'll assume that I can use the latest stable 0.10.x (0.10.38)...but how about 0.12.x? Also, can I go back to 0.10.26 if I need to? (Certain managed hosting providers only support 0.10.26 or 0.10.31.)

It would be nice to have some guidance on what works and what doesn't (or at least a description of the linkages between NTVS and Node.js).

Thank you.

**Comment by mousetraps** [comment]
The most recent versions of node get the most testing, but we support stable versions of node. 
* >= v0.10.21
* NOT v0.10.34 and 0.10.35

If debugging or profiling is not working for you in some other versions, then let us know so we can fix it.

The primary connection is:
* nodes debugging and profiling APIs are not stable.
* core team is small, node/iojs are rapidly evolving, we can't test everything all the time, and can't fix issues we don't know about.

In theory 0.10.x (with above restrictions) and 0.12.x just work because minor/patch changes shouldn't break anything by definition.

We are considering ways to increase visibility of the currently supported versions of node/iojs so any ideas are much appreciated. :-)

**Comment by mousetraps** [comment]
Really if anything isn't working as expected, let us know... But debugging and profiling tend to have the biggest issues :-)

**Comment by waynebloss** [comment]
Thank you for clearing that up.

**Comment by waynebloss** [comment]
@mousetraps Do you know of anyone using Node.js v4 with NTVS yet?

**Comment by mousetraps** [comment]
I don't know of specific people, but we've certainly been testing with it :smiley:. There are some issues with profiling, but everything should work beyond that with the latest Dev build. http://github.com/Microsoft/nodejstools

**Comment by mousetraps** [comment]
Oops wrong link. Dev builds here. https://github.com/Microsoft/nodejstools/releases

**Comment by waynebloss** [comment]
Great! I just installed the dev build today, thanks!
