### ISSUE TITLE
Detect that IntelliSense has stopped working, and automatically offer to delete analysis file

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#64]
This will help us provide a gracefully degrading experiences in cases like #63

**Comment by mjbvz** [comment]
With [NTVS 1.2 Beta](https://github.com/Microsoft/nodejstools/releases), we default to using our new ES6 IntelliSense experience backed by Typescript. This is the modern IntelliSense experience we are targeting, and it should be much more stable and pick up new features and fixes much quicker than our current static analysis engine.

Closing this issue since ES6 IntelliSense in NTVS 1.2 Beta fixes many of the perf problems and instability with IntelliSense.
