### ISSUE TITLE
Single MSI for all Visual studio instances installed on machine

### ISSUE THREAD

**Issue by rkavalap** [Microsoft/nodejstools#701]
Having to download and install multiple msi for different versions of visual studio seems a little outdated. You should just release one single msi regardless of which visual studio version is installed. - 
Identify all the visual studio instances from the registry hive and install nodejs tools addon. 
Currently Resharper does this for its setup. 
I am also wondering why nodejs tools addon is not part of VS setup as an option.

**Comment by mjbvz** [comment]
Thank you for the suggestions.

We are looking to move away from MSIs for installation so that we can support some new Visual Studio use cases (such as [Lightweight VS Install](https://blogs.msdn.microsoft.com/vcblog/2016/04/01/lightweight-cpp-installation-in-vs-15/) #821) and also automatically update NTVS.

#956 tracks appearing in the VS setup list.

Closing this issue in favor of those two. Keep an eye out for more of work in this area, it's really something we want to improve. 

Thanks.
