### ISSUE TITLE
Problem opening multiple views of the same JavaScript (.js) file using 'window > new window'

### ISSUE THREAD

**Issue by liamprescott** [Microsoft/nodejstools#765]
# Problem opening multiple views of the same JavaScript (.js) file using 'window > new window'

## Bug:
Cannot open multiple views of the same JavaScript (.js) file using Visual Studo command 'window > new window'.

### Expected result
Second instance / view of the file opens in a new tab

### Actual result
**Get a dialogue message:**
'The document [FILE LOCATION].js is already open. Do you want to close it? Yes / No'

Clicking Yes = Closes current tab and opens a new tab. Therefore still only one tab open.
Clicking No = No action (close dialogue)

### Project types affected
NTVS projects (.njsproj) e.g. 'Blank Node.js Web Application'.

## Verification / testing
Works as expected when:
- JavaScript file (.js) in 'standard' project type e.g. 'ASP.NET Web Application'
- JavaScript file opened outside of any project

## Environment
- Windows 7 Professional, Service Pack 1
- Visual Studio 2015 Version 14.0.24720.00 Update 1
- NTVS v.1.1

**Comment by mjbvz** [comment]
This problem does not seem unique to NTVS and can also be triggered by "open-with" for some other text editor options. 

I think the root cause is in `InitializeLanguageService` where we throw an exception if the `currentSid` does not match the `langSid`. Just skipping the exception seems to work, but we need to make sure this will not introduce regressions.
