### ISSUE TITLE
ES6 Syntax

### ISSUE THREAD

**Issue by RamIdeas** [Microsoft/nodejstools#77]
**Can we get support for ES6 syntax in Visual Studio, please?**

With transpilers like Babel allowing us to safely and powerfully develop using the syntax right now, VS seriously lacks the support to match.

See [here](https://github.com/lukehoban/es6features) for a full list but, in my opinion, features most likely to improve a developers efficiency (ordered in descending impact) are:

- [ ] Object / array destructuring
- [ ] Object literal shorthand notation
  - [ ] Inferred property names from variable (e.g. `var name = 'John', person = { name }`)
  - [ ] method shorthand (e.g. `var person = { getName() { return name }`)
  - [ ] computed property names (e.g. `var prop = 'name', val = 'John', person = { [prop]: val }`)
- [x] Generator functions
- [ ] Arrow functions
- [ ] for..of loops
- [ ] Module definitions: `export default` / `export var`
- [ ] Module usage: `import xyz from 'xyz'` / `import { abc } from 'xyz'`

**I'm only asking for syntax not intellisense -- just highlight correctly and don't show red squiggles**

**Comment by johnrezzo** [comment]
I would really appreciate ES6 support too, intellisense included. Thanks for the great work.

**Comment by jasonwilliams200OK** [comment]
The best place for feature request for VS is http://visualstudio.uservoice.com/. There is an open feature request for ES6 Modules http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/7017377-support-for-es6-modules. Please open this where they are actually counting the votes. 

It's a shame that Microsoft JSLS and the underlying JS AST (unlike AST for CSS, Less, Sass) classes are all internal, even in VS2015! which means that third party extensions cannot extend on MS-JSLS to augment VS JS capabilities. Some people were asking for it on Twitter and GitHub since last year, but it didn't happen in VS2015. Having JSLS reusable will probably make VS the best tool for JavaScript in market, with third-party extensions bringing the feature-set up to the speed and adding more fascinating features/enhancements.

@mousetraps, IMO this issue should be closed here as the support to ES6 VS is not confine to v8/node.js.

@RamIdeas, please share the uservoice links here once you lodge feature request(s) there (preferably keep those as separate features like you did here)., so we can upvote it there. :)

**Comment by mousetraps** [comment]
@jasonwilliams200OK Thanks for your input, but this actually does belong here as well.

We *used* to use JSLS (it is extensible btw) and still do for client-side code (switch the "build action" to "content" instead of "compile"). JSLS was nice and accurate, but the problem was that it works by executing your code, which simply did not scale well to the large node projects that people were working with.

So sometime after Beta 1, we replaced JSLS with our own homegrown static analysis engine for Node.js code. The unfortunate side effect of this is that we cannot simply piggyback on JSLS for any new features. The fortunate side effect of this is that NTVS is open-source, and we're happy to accept contributions. :wink:

FWIW we do plan on prioritizing ES6, but it's a lot of work for our small core team so thanks in advance for your patience. Here's a little more info on [ES6 support so far](https://nodejstools.codeplex.com/wikipage?title=io.js), including when you can expect to see squigglies.

**Comment by RamIdeas** [comment]
In the meantime is there a way of getting Visual Studio (2015 RC) to run my node.js code? Currently, it fails the "build" and opens up the error list (after asking if I would like to run from the last successful build).

I moved to Sublime Text to write all my code but the debugger would really help right now -- `console.log`s create a very slow iteration cycle.

**Comment by mousetraps** [comment]
This feature is currently available if you switch on the new ES6 IntelliSense Preview mode, available in the [latest NTVS release](https://github.com/Microsoft/nodejstools/releases). Please check it out and file issues as you run into them!
