### ISSUE TITLE
With ES6 preview, intellisensse cannot read npm packages

### ISSUE THREAD

**Issue by alanpurple** [Microsoft/nodejstools#774]
with 'Full Intellisense' it's okay ( ex) mongoose and every installed packages )

but with 'ES6 preview' Intellisense sense nothing, only sense libraries with files within project

this is very serious since node.js officially support many ES6 features.

or is there a plan to fix this?

**Comment by mjbvz** [comment]
Could you please clarify what is going wrong with the Intellisense. Are you not seeing any Intellisense for packages that you have NPM installed? A list of repo steps + the expected vs the actual behavior would be helpful.

Also, what version of Visual Studio are you using and what version of NTVS?

Thanks.

**Comment by alanpurple** [comment]
Windows 10 pro x64 + VS 2015 community edition,  yes Intellisense sense nothing with ES6 preview setting, but works fine with 'Full Intellisense' setting

I just change settings to 'ES6 Preview', that's all I did

Intellisense does not recognize installed packages, packages api, function, etc, everything

**Comment by mjbvz** [comment]
Are you using a preview release of NTVS?

Also, can you please let us know what specific version of visual studio you are using. Specifically, is it 2015 Update 1 or 2015 Update 2? 

The 'ES6 Preview option' requires Visual Studio Update 2 in the latest builds of NTVS. If you are on Update 1, the intellisense behavior will be similar to what you describe.

**Comment by alanpurple** [comment]
@mjbvz  yes I'm using VS2015 update1 with ntvs 2016-3-22 dev builds

**Comment by mjbvz** [comment]
Thanks. I believe that is the expected behavior for that combination. We should make it more clear when ES6 Intellisense cannot function properly with a given VS version.

If you can, please try out the [NTVS v1.2 Alpha build we just released](https://github.com/Microsoft/nodejstools/releases/tag/v1.2.Alpha). You also need [Visual Studio 2015 Update 2](https://www.visualstudio.com/en-us/news/vs2015-update2-vs.aspx). Make sure to grab the full update 2 release, not the release candidate.

**Comment by alanpurple** [comment]
@mjbvz with VS 15 preview + NTVS 1.2 alpha, almost same, with a few resolved

I think this is related to #434
