### ISSUE TITLE
Auto-dts should not be enabled for typescript projects

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#776]
This floods the error list because the versions are often mismatched.

**Comment by mjbvz** [comment]
I think this is caused by a race condition. We already try to gate this scenario, but it is an opt out flag that is set when we see any typescript files. One way to accomplish this would be to use the project settings themselves, but these can only be checked on the main thread, which is why we created the opt out variable in the first place.

Looking into better a fix.

**Comment by mjbvz** [comment]
Actually, the project property for `IsTypeScriptProject` is only set after files are added so it probably would suffer from the exact same problem.
