### ISSUE TITLE
Feature: Copy import reference and paste in typescript file

### ISSUE THREAD

**Issue by gautamsi** [Microsoft/nodejstools#78]
I am working on a large nodejs/js typescript project, it is conversion from a large c# project. I am having challenge in adding import statement in each file. there are 100s of class files which I do not want to combine in a file.

it would be nice to right click a .ts/.js file in solution explorer and paste the import statement in open .ts file. it should keep track of where it is pasting use proper relative path like - import fileName = require("./subdir/fileName"); or require("../../grandlvldir/parentlvldir/filename");

I do not have any experience in writing extension project otherwise I would have done it.

**Comment by mjbvz** [comment]
This sounds like an interesting feature, but I believe it is beyond the scope of anything we are planning for this tooling. Closing for now.

**Comment by mousetraps** [comment]
Re-opening - while we won't necessarily implement it ourselves any time soon, we'd certainly be willing to accept a PR. 

If anyone is interested in tackling this, then drag-and-drop into the file is the way to go... not right-clicking... so that we're consistent with the HTML + JS script tag drag-and-drop experience

**Comment by mjbvz** [comment]
Closing again as out of scope / external . This is a feature that the TS team would likely handle now that they power the main NTVS editing experience.
