### ISSUE TITLE
Test Explorer doesn't run mocha tests with fs.readFileSync and possibly more

### ISSUE THREAD

**Issue by MystK** [Microsoft/nodejstools#8]
When I have unit tests that call fs.readFileSync, the test does not show up in Test Explorer, but the code runs fine.

fs.readFile also works fine.

**Comment by mousetraps** [comment]
Hmm, could you provide some sample code?  I can't repro this using the code below. 

```javascript
var assert = require('assert');
var fs = require('fs')

describe('Test Suite 4', function() {
	it('Test 3', function () {
		var txt = fs.readFileSync('hello.txt');
		console.log(txt);
		assert.ok(true, "this should pass");
    })
})
```

Also just verify that the test framework is marked as "mocha" for every file and try building the project. (Ctrl+Shift+B) We currently discover tests when you modify a file, but you'll have to build when you add new files.

**Comment by MystK** [comment]
The code you provided works, but when the fs.readFileSync is moved out of the test, such as when requiring other files, it doesn't show up in test explorer.

```javascript
var assert = require('assert');
var fs = require('fs')
var txt = fs.readFileSync('hello.txt');

describe('Test Suite 4', function() {
    it('Test 3', function () {
        assert.ok(true, "this should pass");
    })
})
```

The above does not work. This is an issue because my test code is something like this.

```javascript
var app = require('server');
describe('Test Suite', function() {
    it('Test', function () {
    })
})
```

And the server has a fs.readFileSync.

**Comment by mousetraps** [comment]
Just looked into this. The issue appears to be that test discovery is running in a different path than expected (try running the file from a different directory, and you'll see what I mean).

In general, it's best to do something like ```path.join(__dirname, filename)``` instead of just the filename to make sure that your working directory is what you're expecting it to be.

Anyways, the fix I'll commit soon will mitigate the confusion by setting the process directory to the project folder, and also print out the working path in the beginning so that it's easier to debug similar issues in the future.
