### ISSUE TITLE
What version of node.js do you recommend for NTVS 1.2 Alpha??

### ISSUE THREAD

**Issue by michaelderemer** [Microsoft/nodejstools#801]
The previous installers had node chakra installed with it. I see you have preliminary support for node v6.x. I don't really care what version can you provide a link in your https://github.com/ms-iot/ntvsiot page so as i take care of prereqs i can make sure i install a tested version of node at the correct time.

**Comment by mousetraps** [comment]
NTVS itself does not ship with any particular version of node and instead works which whichever version of node you have installed. The NTVS iot extension ships with NTVS, plus a bunch of other stuff to light up the node chakra iot functionality. 

It sounds like you're looking for the node chakra iot functionality. If so, please file an issue in https://github.com/ms-iot/ntvsiot requesting support for the latest version of NTVS. 

Otherwise just use a version available from nodejs.org (we recommend node v5.x because it includes npm v3, but node v4.x is the most recent LTS release and is likely more stable.)
