### ISSUE TITLE
Attempting to get NPM version in the Node.js interactive window fails

### ISSUE THREAD

**Issue by MarkStega** [Microsoft/nodejstools#811]
I am trying to get version info in the Node.js interactive window.

I get:

`Node.js interactive window. Type .help for a list of commands.
> .npm version
Please specify a valid Node.js project or project directory. If your solution contains multiple projects, specify a target project using .npm [ProjectName or ProjectDir] <npm arguments> For example: .npm [MyApp] list`

**Comment by mjbvz** [comment]
Does your solution have multiple node projects?

In that case, for `.npm` commands, you must explicitly specify which of those projects you are targeting. For example, if you had a project called `WebApp`, you have to run. `.npm [WebApp] version`

This experience is not great since `npm version` should not really require a target project, but I'm not sure we want to try to determine which npm commands require a project and which ones don't.

**Comment by MarkStega** [comment]
OK, so I tried ".npm [Optimiser.Web.NG]" which is the name of the only project in the solution that uses npm/nodejs. This failed with the same error message. It is not a Node.js project of that matters. So I tried ".npm [d:\solutions\ohi\optimiser\src\optimiser.web.ng] --version" and this returned 3.7.3

Overall this seems really clumsy.

**Comment by mjbvz** [comment]
So "Optimiser.Web.NG" is not a NTVS Node project? You can double check this by looking at projects file type (`Optimiser.Web.NG.*proj`). It should be listed as `Optimiser.Web.NG.njsproj` if it is a NTVS project.

If it is not a NTVS Node project, I believe you may be running into this issue: #480.

We currently do not support using the Node interactive window for to run `.npm` commands for non-NTVS-Node projects. The PR to improve this is already out, #808. After that is merged, you should not have to use the full path to the project, and `.npm [Optimiser.Web.NG] --version` should work. The project selector part in the brackets will still be required if there is more than one project in a solution, because we need to know where to execute the `.npm` commands.

**Comment by MarkStega** [comment]
No, "Optimiser.Web.NG" is an xproj not an njsprod. The xproj type is what you get when you create and ASP.Net 5 project (still the old name in VS) and many of the examples use npm to manage development packages such as gulp. I think that 480/808 in concert will help a lot.
