### ISSUE TITLE
What version of tools such as npm are used by NTVS

### ISSUE THREAD

**Issue by MarkStega** [Microsoft/nodejstools#812]
Using VS2015 Update 2, Community edition

It appears that if I let NTVS do the population of node modules that NPM V2 is being used as I get a source tree deeper than Windows GUI tools allow.

I have nodejs 5.9.1 installed with npm 3.7.3 so if I do an 'npm install' at the command line I get the v3 'flattened' node_modules directory.

I also have several gulp scripts that run properly from the command prompt but inside the task runner explorer the script fails.

I would have thought that the NTVS diagnostic window would help but it doesn't have any info about the underlying tooling.

**Comment by mjbvz** [comment]
To help with the investigation, try running `.npm --version` in the "Node Js Interactive window" to see what version is being used.

The logic for selecting the version if here: https://github.com/Microsoft/nodejstools/blob/904751f68e3bce5082c2a8e87bfccfb34351473b/Nodejs/Product/Nodejs/Nodejs.cs#L54

NTVS looks for the tool paths in the registry first, then the PATH, then "Program Files".

If the npm version does not match what you expect, let us know and we can look into the issue further.

**Comment by MarkStega** [comment]
The versions reported are npm 3.7.3 and node 5.9.1;

Perhaps we should go back to the symptom:

Since I have determined the the npm version is 3.7.3 at the interactive NTVS window perhaps the issue is with what is actually running when VS restores npm packages. The window that opens shows output from bower\npm with the first command being 'npm install'; I've never installed bower into node. Do you know if this is somehow 'built in; to VS? I wonder if this is where npm v2 is hiding.

**Comment by mjbvz** [comment]
We use the title "Bower/NPM" as a generic title for the output window, it does not imply that bower has been installed.

Is this a *.njsproj project you are working in this time?

**Comment by MarkStega** [comment]
No this is not an nsproj, this is an xproj that uses npm & jspm for the web components.

**Comment by mjbvz** [comment]
Could you please clarify the expected vs actual behavior then.

The original bug mentions NTVS populating the node modules, but I don't think would be the case if you are not in in NTVS project. Are they getting populated by another tool perhaps?

The NodeJs Interactive windows supports custom Node and npm exe paths, but only for `* njsproj` projects (this is controlled by the Path to Node.exe setting on the project). Otherwise, NTVS and the interactive will use standard logic to decide what copy of Node/Npm to use: https://github.com/Microsoft/nodejstools/blob/904751f68e3bce5082c2a8e87bfccfb34351473b/Nodejs/Product/Nodejs/Nodejs.cs#L54

**Comment by mousetraps** [comment]
I suspect the issue lies in: Tools > Options > External Web Tools, which currently prioritizes the npm that ships bundled with VS over the user-installed version. 

As Matt described... With NTVS, we strive to use the same version that would be used were you to open a command prompt from outside of visual studio. We are also chatting with the VS web tools team to ensure that the rest of VS follows this model, but it sounds like they haven't gotten around to it just yet.

**Comment by MarkStega** [comment]
I believe that your question of what tool is being used is germane. I searched the directory where VS2015 is installed and discovered what I believe VS is using to populate the node_modules directory.

In "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External" there are .cmd files for bower, grunt, np,. node and others. Opening a command prompt in that directory and executing 'npm version' shows a node.js version of 0.10.31 and an npm version of 1.4.9

**Comment by MarkStega** [comment]
@mousetraps We posted in the same minute

It was Tools > Options > Projects and Solutions > External Web Tools

The defaults do use the bundled tools... Keep after the VS Web Tools team :-)

**Comment by mjbvz** [comment]
Closing since I believe the original question has been answered and it was an external issue.
