### ISSUE TITLE
callback never hit in javascript unit test toplevel

### ISSUE THREAD

**Issue by panlina** [Microsoft/nodejstools#830]
I have this in a javascript unit test source:
```
var fs = require('fs');

function f() {
	fs.writeFile("a.txt", "a", 'utf8', function () {
		fs.writeFile("b.txt", "b", 'utf8');
	});
}

f();

exports['foo'] = function () {
	f();
}

```
`f` is supposed to create 2 files, a.txt and b.txt. The issue is that, when `f` is invoked from inside a test method, it works as expected, but when it is invoked from toplevel--by building the project, updating the Test Explorer--only a.txt is created. Actually the callback is never called and this happens for any async callback.

**Comment by mjbvz** [comment]
I believe is somewhat expected because you're using async code. When `f` returns and `foo` returns, there is no guarantee either `a.txt` or `b.txt` will exist. Node will wait for the callbacks to complete before existing, but the test runner may not.

Try changing both calls to `fs.writeFileSync` to check if this is the root cause. Have you looked into making the tests async?

**Comment by panlina** [comment]
I agree that a.txt or b.txt is not guaranteed to exist when f() returns, but why the callbacks are 'truncated'? Why doesn't NTVS wait for all callbacks just like any regular node run?
My scenario is to prepare some data at the same time defining the test methods. For sure I can change it to use only sync calls, but it is a big restriction on writing node.js code.
Is it because NTVS want to avoid the unit test definition running too long?

**Comment by mjbvz** [comment]
NTVS is acting like many test runners do. Unless told otherwise, it assumes that tests are function scoped, so once the test function returns, the test is over.

The example test code is not valid. And because the behavior in the example is undefined, I do not see a good reason to support it.

Please rewrite the test to be async and let us know if you run into any issues with that. Thanks.
