### ISSUE TITLE
How does NTVS compare with Visual Studio Code?

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejstools#86]
Watching Build I saw https://code.visualstudio.com/ launched and wondered what the advantages of each is? Certainly VS + NTVS offers a lot more functionality. But what if just deving a node based HTML app / website?

**Comment by mousetraps** [comment]
Good question.

Right now it's tough to really provide much guidance because it's only day 2, and we're genuinely interested in listening to user feedback so that we can learn how to best improve the overall Node.js dev experience going forward.

The advantages of NTVS are - as you mentioned - the feature-set and maturity of the product. From a quick glance... with VS, you're going to get more advanced debugging (conditionals, remote debugging, etc), unit testing, cloud integration, more semantically-correct IntelliSense for JavaScript using the NTVS static analysis engine (I believe VSCode will just show you all identifiers unless you're using TypeScript), profiling, all the awesome VS extensions already available (e.g. web essentials, package intellisense, task runner explorer, [cool IoT stuff](http://ms-iot.github.io/content/win10/samples/NodejsWU.htm), etc.), starter project templates, npm integration, interactive window...

On the other hand, VSCode is cross-platform, super  lightweight, has a file/folder-based project system, code actions (lightbulbs), more seamless switching between client-side and server-side editing experiences, and can potentially evolve more quickly since it's being built from the ground up and isn't limited to long-established VS-isms.

So ultimately... if VSCode works for you, that's awesome! If NTVS works for you, also awesome! If you want to use both, but for different purposes... you get where I'm going. :smiley: I personally suggest is playing around with VSCode now, and if you like something in VSCode that's not in NTVS or vice versa, let us know.

**Comment by SteveALee** [comment]
Thanks! A great answer.

From some of the comments during /build it seems Code is focussed more on the tight edit/debug loop though you can add commands to it. VS Enterprise and to a lesser extent Pro address the big picture. VS is great and now there is community it is usable by open source projects. I've not yet decided if VSCode + command line build is the way to good for me with VS for the tough debugs etc.

I think you are correct about intellisense support - they talked about levels of support for different languages. I'm not ready for typescript just yet. :)  

PS Am going to try Vorlon too for client debug 

Will certainly let you know of any features requests etc

BTW I just updated to VS 2015 RC and can't find NTVS - is it not available yet? But I have other problems as windows 10 tools won't install either. Might have to roll back to VS2013.

**Comment by SteveALee** [comment]
This [recording](https://channel9.msdn.com/Events/Build/2015/3-680) of the #build2015 presentation explains more.
