### ISSUE TITLE
Project templates to support RESTify

### ISSUE THREAD

**Issue by JasonHaley** [Microsoft/nodejstools#873]
It would be nice to have other options besides Express - especially if we a only creating a 'WebApi' type  of site.  I'm looking at needing to use RESTify on a project and would love to have template for it instead of starting off with a blank one. 

Is that on any milestone?

**Comment by mjbvz** [comment]
We are not tracking this currently, but are always willing to take a pull request for this sort of work.

Anyone interested in adding a new template can look at the [existing project templates]( https://github.com/Microsoft/nodejstools/tree/master/Nodejs/Product/Nodejs/ProjectTemplates) as a starting point. Here are the[ build instructions for NTVS](https://github.com/Microsoft/nodejstools/wiki/Build-Instructions).

Thanks.

**Comment by mjbvz** [comment]
Actually, instead of adding more templates to NTVS, we're looking to support a more Node style of development, integrating with tools like Yo and creating other more generic project templates. Look for upcoming work in this area. 

Closing this in favor of that work, but thanks again for the suggestion. We'll definitely try to support RESTify better, I'm just not sure more project templates are the way we want to do this.
