### ISSUE TITLE
Error while running the tests in debug mode

### ISSUE THREAD

**Issue by rnagpal** [Microsoft/nodejstools#877]
Hello All,

I'm a newbie to Node.js and trying to run existing tests we have in our project. I've installed latest NTVS extension for VS 2013 and I'm able to see all the tests in Test Explorer.

I'm getting the following error while "Debugging" any test. The test run successfully when I simply "Run" them. I've installed mocha in "dev" as well as "global" environment.

_The program '[1] node.exe @ tcp://localhost:52250/#ping=0' has exited with code -1 (0xffffffff)._

Same issue with NTVS extension for VS 2015. I'm able to debug the tests in VS Code though, so most likely it's a config issue for my NTVS extension in VS and I'm hoping to fix that and be able to run the tests in VS.

Here is some other output I see when I click the Output link just next to the failing test.

_Result StandardOutput:	mocha.json options file not found. Using default values: { ui: 'tdd', reporter: 'tap', timeout: 2000 }

Result StandardError:	Debugger listening on port 52250_

Am I missing any step configuring my test environment so that I can debug the tests from Visual Studio?

**Comment by rnagpal** [comment]
I'm using Node.js version 4.2.6

Is there any place where I can get more detailed logs on what's happening?

**Comment by mjbvz** [comment]
Thanks for the report.

What version of NTVS are you currently on and what are the specific versions of visual studio? Both of these can eb found in `Help -> About Visual Studio`

I think that `_Result StandardOutput ...` and the -1 exit code are both expected behaviors in this case. The problem may be the breakpoint mapping itself. Out of curiosity, what happens if you add a `debugger` statement to one of the tests and debugging? Does the debugger stop on that statement?

For more info, you can also try going to `Tools -> Node.js Tools -> Diagnostic Info` and enabling the 'Enable Node.js Tools Live Diagnostics output pane' to see if this prints any more useful info to the output window.

**Comment by rnagpal** [comment]
I was able to figure the issue out. That was a timeout issue. I didn't had a mocha.json present for my test, so it was using the default value of 2000ms(2 sec) to timeout my test. After adding teh mocha.json and overriding the timeout, I was able to debug.
