### ISSUE TITLE
Unable to exclude typings folder from project

### ISSUE THREAD

**Issue by beautifulcoder** [Microsoft/nodejstools#883]
Hello, recently upgraded to NTVS 1.2 alpha. I am able to exclude `typings` from my project file and tell git to ignore this. But the moment I close and reopen the solution, it returns. Is there no way to exclude this? It's causing tools like R# to freak since it tries to do static analysis on those TypeScript files. I am also not sure I like the idea of dumping dependencies into every solution. Seems like there is a better a way to provide IntelliSense. I am using ES6 preview.

**Comment by beautifulcoder** [comment]
Might have spoke too soon. There is a way to exclude folders from code analysis in R#. Still, isn't there a better way?

**Comment by beautifulcoder** [comment]
One more! I think I found a bug with the typings folder. Every time I close / open the solution it tacks on yet another duplicate *.d.ts file. With a team of engineers, everytime someone reopens the solution it makes .njsproj bigger.

**Comment by mjbvz** [comment]
Thanks for the report.

Here's some more info about the typings folder: https://github.com/Microsoft/nodejstools/wiki/Automatic-Typings-Acquisition

To summarize, `typings` must be included in your project for ES6 Preview for Javascript projects for VS 2015. This is not required in VS15. If this is a typescript project, you may be running into the same issue #872. The next alpha release should correct a few issues around `typings`.

The second issue sounds like what was fixed by #868. This will also be in the next alpha.

**Comment by beautifulcoder** [comment]
Ah, glad to hear this is not an issue in VS15 and that the bug has been fixed. Was getting kinda worried in the direction the tooling was taking.
