### ISSUE TITLE
How to fully remove NodeJSTools from Visual Studio?

### ISSUE THREAD

**Issue by IPWright83** [Microsoft/nodejstools#884]
I installed NodeJS Tools for Visual Studio to help out with some Node development. But unfortunately I started getting some errors:

> Error - Cannot load local packages. Error - Cannot load global packages. System.AggregateException: One or more errors occurred. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json at 'C:\source\Edge\MooD16\MooD.LandscapeExplorer\node_modules\karma\node_modules\mime\package.json': Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

> The following error occurred:

> Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject. ---> Microsoft.NodejsTools.Npm.PackageJsonException: Error reading package.json. The file may be parseable JSON but may contain objects with duplicate properties.

This looks like this https://github.com/Microsoft/nodejstools/issues/208 issue but attempting to remove duplicates/install a new version didn't seem to fix the issue. So I decided to just go for the un-install approach.

After un-installing however, I'm still getting exactly the same issue. So I'm guessing that NodejsTools haven't cleaned themselves up properly, or something similar.

Is there a way I can really remove/disable start up in Visual Studio? I've searched for NodejsTools files and can't find any and I've checked the install path c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Node.js Tools for Visual Studio but there must be some other bits left over.

**Comment by mjbvz** [comment]
Sorry you are running into this problem, we'll take another look at fixing the issue.

Regarding the uninstall, do you still see any Node.js tools listed in `Tools -> Extensions and Updates`? Depending on how NTVS was installed, you may have to uninstall it using the Windows `Programs and Features` settings pane. Do you NTVS listed there?

**Comment by IPWright83** [comment]
I installed via an MSI and un-installed via Add/Remove Programs. There is
no trace of it either in there or the list of installed extensions.

I've worked around the issue - copying node_modules from another machine
has got me going but if this error is coming from nodejstools then
obviously needs sorting.
On 25 Apr 2016 19:43, "Matt Bierner" <notifications@github.com> wrote:

Sorry you are running into this problem, we'll take another look at fixing
the issue.

Regarding the uninstall, do you still see any Node.js tools listed in Tools
-> Extensions and Updates? Depending on how NTVS was installed, you may
have to uninstall it using the Windows Programs and Features settings pane.
Do you NTVS listed there?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Microsoft/nodejstools/issues/884#issuecomment-214475514>

**Comment by mjbvz** [comment]
Ok, so it sounds like you are unblocked now at least. Do you still see any remnants of NTVS in your Visual Studio, such as under `Tools` or in the project templates?

You can try running the `devenv /updateconfiguration` or `devenv /setup` from a Visual Studio command prompt to make sure VS had updated the extensions it knows about. You can also check to see if NTVS is listed in `%LOCALAPPDATA%\Microsoft\VisualStudio\14.0\Extensions\Microsoft`

**Comment by dkgibson** [comment]
I installed Node.js as part of a Visual Studio Community 2015 install.  When I attempt to uninstall, change, or repair the installation, I get a 2502 and 2503 error from the installer.  How do I get rid of node.js????  Deleting it in \Program Files doesn't get rid of it

**Comment by mjbvz** [comment]
@dkgibson Just to clarify, you are talking about *Node.js Tools for Visual Studio* (NTVS) and not *Node.js*, correct?

How were you trying to uninstall, through "Add or remove programs"?

You can also try running the installer as an administrator, by opening an administrator command problem and pasting in the path of the NTVS msi.

Please let me know if that helps. Thanks.

**Comment by dkgibson** [comment]
This was Windows 10, so it was using "Programs and Features", and it was trying to uninstall node.js, not the tools you refer to.  However, reporting the problem here may be bogus, as I subsequently encountered the same error #2503 & 2502 when attempting to uninstall several other components that were installed as part of VS 2015 Community.  So, I used the Windows "Restore Point" that was created as prior to the VS 2015 install.  That got rid of all of the VS-installed components that wouldn't install, and then I went through Program Files and Program Data and deleted all the left-over stuff, including node.js.

So, I don't think this is your error.  I'm going to install Visual Studio 2005 (yes, 2005), which I've never had a problem with.

**Comment by mjbvz** [comment]
Sorry, that sounds like a pretty bad experience. My guess is that you are running into some sort of permissions issue, but I can't say for sure. Going back to VS 2005 may be one solution, but be aware that you're going to be missing out on a lot of improvements and losing support for most extensions. And, while VS2005 has had a much longer time to stabilize, it may not work as well in year 2016 workflows. 

Since the problem sounds greater than just NTVS, let me know if you'd like to try to find a contact on VS to look into this issue.

I'm going to go ahead an close this issue. @IPWright83 please let me know if you are still running into the original problem and we can continue looking into a fix. Thanks.
