### ISSUE TITLE
NTVS Update Packages Hangs

### ISSUE THREAD

**Issue by AcousticGuitar** [Microsoft/nodejstools#885]
**Problem**
Visual Studio hangs when attempting to NPM update package list.  Subsequent Install NPM package also hangs.

Step 1) Create a new Node console application, attempt an install of an NPM package
![installnewpackage](https://cloud.githubusercontent.com/assets/10676026/14790300/450d8adc-0ad6-11e6-8c2f-bc09f28aa743.PNG)

Step 2) Note the package list is outdated...
![outdated](https://cloud.githubusercontent.com/assets/10676026/14790335/6e20f74c-0ad6-11e6-9d5e-c74c7896139a.PNG)

Click on Refresh...

Output window shows this:
![hang](https://cloud.githubusercontent.com/assets/10676026/14790403/c45ccd20-0ad6-11e6-9404-2323fa4f4de0.PNG)

GUI shows this:
![gui](https://cloud.githubusercontent.com/assets/10676026/14790431/ec0ec67a-0ad6-11e6-984a-170c2bc8f63c.PNG)

Waited about 30 minutes, as application is hung...

Current Version of VSTS
![nodetools](https://cloud.githubusercontent.com/assets/10676026/14790500/318bd774-0ad7-11e6-8de9-57e650e9156d.PNG)

Just recently upgraded node to:  V5.9.1 in order to ensure I get the 'flattening' of module dependencies so that many NPM packages will not bump into 256 directory path limit. 

Please advise.

**Comment by mjbvz** [comment]
Thanks for the report. Here are a few suggestions:

I'd try updating to the latest NTVS 1.1 build if you have a chance: https://github.com/Microsoft/nodejstools/releases/tag/v1.1.1 I'm not familiar with every fix that has gone into 1.1 since the 1.0 release, but it may improve things. The NTVS 1.2 Alpha dropped support for VS 2013

Your package cache may have also gotten into a bad state, so you can try clearing and rebuilding it. Open `Tools -> Options` and navigate to `General -> NPM`. There should be a button marked `Clear Cache` that will empty our the current package cache. You'll have to download the package list again, but it may get you back into a good state.

Let me know if any of those work.

**Comment by AcousticGuitar** [comment]
Will do and thanks for feedback, I'll report back results tomorrow.

**Comment by paulvanbrenk** [comment]
We no longer cache the registry locally, so this should no longer happen
