### ISSUE TITLE
Errors with Browser/Node.js-side editing

### ISSUE THREAD

**Issue by anubmat** [Microsoft/nodejstools#903]
NTVS scenarios testing: 
The directory display name didn't change to "hello(node)". It also didn't change to "hello(browser)" after right clicking the directory and selecting "Set as content (Browser code)". 
 
Expected:
The directory display name will switch types when Selecting the different mode.("Set as Compile(Nodes.js code)" or "Set as content (Browser code)"). 
 
Actually: 
The directory display name can’t be changed to “hello(node)”/ "hello(browser)".

**Comment by mjbvz** [comment]
Thanks.

@mousetraps We explicitly disable this behavior when ES6 Intellisense preview is on: https://github.com/Microsoft/nodejstools/blob/d966849ae462c543313291ad20d419a27c8e1fc7/Nodejs/Product/Nodejs/Project/NodejsFolderNode.cs#L107.

I updated the test matrix to note this, but just want to confirm this is the expected behavior.

**Comment by mjbvz** [comment]
Closing as by-design. Updated the test matrix to note this.
