### ISSUE TITLE
Is it possible to pause a node.js process and attach VS to it and debug?

### ISSUE THREAD

**Issue by jack4it** [Microsoft/nodejstools#91]
will "debugger" statement work in node.js?

**Comment by jinglou-** [comment]
Are you thinking of remote debugging by attaching to the process?  If so, the answer is yes.  Check out our documentation on "advanced debugging" here http://nodejstools.codeplex.com/wikipage?title=AdvancedDebugging.  If you are thinking of something else, please tell us a bit of your scenario.  Thanks.

**Comment by mousetraps** [comment]
Yes, it is possible. You can either set breakpoints or use the debugger statement. See the [Local Attach Documentation](http://nodejstools.codeplex.com/wikipage?title=AdvancedDebugging#local-attach).

Out of curiousity, though, what is the advantage of using the debugger keyword in VS rather than using breakpoints? I can come up with a few ideas, but real-world beats contrived any day of the week. :smiley: 

@jinglou- the debugger keyword allows you to suspend execution using code (instead of using a breakpoint.)
```js
debugger; // execution will pause here
```

It can help when it's annoying for one reason or another to set a breakpoint in the debugger (this isn't applicable to VS, but maybe you're adding some lines of code and want to make sure you won't have to re-set the breakpoint every time, which is what you'd have to do debuggers that do not have a combined editor and debugger.)

**Comment by jack4it** [comment]
@mousetraps Thanks for the answer. My scenario is that, I'm working on a Protractor test case which failed and I want to use the promising NTVS to interactively step through it. However, the code run starts from a console command instead of a NTVS project F5. I am able to let node run with --debug, but I need the code to break at some point before I can attach VS debugger onto it. I'm trying and will let you know the results.

**Comment by mousetraps** [comment]
Any reason you can't use --debug-brk?

**Comment by jack4it** [comment]
@mousetraps Thanks for mentioning this. I just tried --debug-brk, program breaks correctly, VS debugger attaching dialog actually shows the node process after refresh. However, once after the refresh, the node debugging server errored out with an connection error. I tried node's own debugger, it works. I do wish NTVS will also work

**Comment by mousetraps** [comment]
Ahh yes, you're right. Instead of localhost:5858, try localhost:5858#ping=0 to work past an [attach issue](tcp://localhost:5858/#ping=0)

**Comment by jack4it** [comment]
@mousetraps The #ping=0 works, thx!
