### ISSUE TITLE
Mocha test discovery only works for one file in ESLint Project

### ISSUE THREAD

**Issue by mattdufeu** [Microsoft/nodejstools#929]
In a "From Existing Node.js code" project on the ESLint codebase, Test Explorer does not list the tests for all files when more than 1 has the TestFramework set to Mocha.

Steps to Reproduce
1. Clone ESLint and do npm install
2. Create a new "From Existing Node.js code" project on the cloned folder
3. Change the TestFramework property of 1 file, e.g. eslint\tests\lib\rules\accessor-pairs.js, to Mocha
4. Build the solution
5. Open Test Explorer and see the tests from that 1 file.
6. Change the TestFramework property of a second file, e.g. eslint\tests\lib\rules\array-bracket-spacing.js, to Mocha
7. Build the solution

Expected Result
Test Explorer should now show both sets of tests.

Actual Result
Only the tests from the first file are visible.

Workaround
Reset the TestFramework property of the first file to empty and rebuild. The second files tests will now appear.

Version
Visual Studio 2015 Enterprise Update 2 14.0.25123.00
Node.js Tools 1.1.31117.00

**Comment by mjbvz** [comment]
Thanks for the detailed report. I confirmed this is also a problem in NTVS 1.2 and am investigating to see if there is a more targeted repo or easy fix here.

For my initial investigation:
* This happens for any tests added after the first one, not just the second.
* We do discover all the test files properly. I can see these are passed into our `mocha.js` unit test runner in `fix_tests`. 
* I did not see this bug when creating a blank app and adding unit tests files manually. I also tried nesting these a few folders deep to see if that was the problem, but we picked up all tests properly in that case too.
* eslint is doing some interesting things with the test running, which may also be the root cause. 

I'll look into seeing if these tests are perhaps not being run properly by the runner or if they are perhaps not reporting back their results.

**Comment by mjbvz** [comment]
I believe this is an eslint specific problem. I only see this behavior in the eslint project and only in the `rules` tests specifically. The root cause seems to be something weird happening with Mocha when we are using it programmatically with these tests.

Here's a simple case that does not involve NTVS that demonstrates this odd behavior:

```js
var Mocha = require('mocha');

var mocha = new Mocha();
mocha.addFile('./tests/lib/rules/accessor-pairs.js');
mocha.loadFiles();

var mocha2 = new Mocha();
mocha2.addFile('./tests/lib/rules/array-bracket-spacing.js');
mocha2.loadFiles();

// Should only run 'accessor-pairs' tests
mocha.run(function (failures) {
    process.on('exit', function () {
        process.exit(failures);  // exit with non-zero status if there were failures
    });
});
```

While this should only run the first set of tests, it ends up running both test files. This does not happen for 'formatter' tests, so it seems to be rule-tester specific. This suggests that eslint rules themselves are doing something bizarre and messing up Mocha.

Until the simple case with the programmatic test works properly, NTVS cannot properly support these tests. Here are some good starting points for that investigation:

https://github.com/eslint/eslint/blob/master/tests/lib/rules/accessor-pairs.js
https://github.com/eslint/eslint/blob/master/lib/testers/rule-tester.js

Thanks.
