### ISSUE TITLE
Investigate downloading typings to node_modules folder for VS2015

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#959]
Investigative task: We've received a lot of complaints about including an additional typings folder in the project, and the experience is much improved in VS "15", but perhaps downloading the typings to the node_modules folder would be a better interim experience for VS2015

**Comment by mjbvz** [comment]
Since this issue was opened, we've [improved the typing acquisition experience](https://github.com/Microsoft/nodejstools/wiki/Automatic-Typings-Acquisition) to better let users know what is going on for now.

For VS15, Typescript is looking into [really improving this experience](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/), but unfortunately, there's limits to what we can do on VS2015
