### ISSUE TITLE
Support latest versions of Node.js v6.x

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#960]
* [x] #934 Breakpoints sometimes not resolving with Node 6.1.0 in files besides main 
  * [x] #935 Hang on Remove Breakpoint in Node 6.1.0

**Comment by mousetraps** [comment]
don't need a separate issue for this

**Comment by mwpowellhtx** [comment]
I am considering using Node for server side simulations and would like to incorporate projects into my VS2013 solutions. Of course, doing so means chasing the tail feathers; I haven't dove into Node waters just yet, but when I do, I would like to stay current with Node as much as possible. Along these lines, what does that mean for NTVS? Besides another chase. Thank you...

**Comment by mjbvz** [comment]
I don't think either of these issues listed above would block you from getting started with NTVS and Node 6, they are just something to be aware of. Node's debugging protocol is not terribly well supported, so new Node releases always could potentially destabilizing NTVS.

To add more context to these issue:

#### #934 
As far as I can tell is the result of changes in in Node. The issue is non-deterministic and I haven't been able to repo it for the past several days. Feel free to give Node 6 a shot and let me know if you run into this issue.

Unrelated to the breakpoint issue, Node 6 also has a regression when certain breakpoints trigger an internal access error in the debugger. Node should pick up the fix shortly: https://github.com/nodejs/node/pull/6928


#### #935 
After opening the issue, I have realized that is effects all versions of Node that I have tested, not just 6.x. It is an edge case that should not be hit very often in normal workflows, but we are looking fix this in the next release.


I would recommend giving NTVS and Node 6 a try. NTVS 1.1 will work with VS2013, but I strongly recommend that you try out NTVS 1.2 alpha on VS2015 instead. It better supports some of the new Javascript features from Node 6, and should be a much better experience all around. And again, please report any bugs you run into.

Thanks.

**Comment by ted-dgk** [comment]
VS2015. Breakpoints never hit using 1.2 and node 6. Also the racing condition causing the app to not run happens the far majority of the time. Sorry to say but this is unusable at this time.

**Comment by ted-dgk** [comment]
Note that nodejs built in debug support DOES work. If you want to place a breakpoint put the word debugger on a line followed by semi-colon. And after a terrible last night and this morning the racing condition is not biting me as bad.

**Comment by mousetraps** [comment]
This issue has been resolved in our v1.2 Beta. Please try it out and let us know what you think! https://github.com/Microsoft/nodejstools/releases
