### ISSUE TITLE
js editor font family and font size setting not working

### ISSUE THREAD

**Issue by edision** [Microsoft/nodejstools#988]
##### Expected Behavior 
js editor panel's font size and font family should be changed, when change the settings.
##### Actual Behavior 

- NTVS Version:1.2 Alpha 2
- Visual Studio Version: 2015 Enterprise
- Node.js Version: 4.4.4

##### Steps to Reproduce
1. tools->options->environment->font and color
2. change the font family and font size. but editor's font size and font family not changed.

**Comment by mjbvz** [comment]
Thanks. 

This seems to be a Salsa (Typescript team) issue as  I only see this bug with ES6 Intellisense enabled, which uses Salsa for editing and analysis. With ES5 intellisense, I can update the font and color as described. 

@billti Can the Typescript team please take a look at this.

**Comment by edision** [comment]
Thanks.
It works.:)

**Comment by mjbvz** [comment]
At least there is a work around if you absolutely need this feature. I strongly suggest that you use the ES6 IntelliSense level otherwise. 

I may take a quick look to see if there are any workarounds we can do on our side, but with us currently trying to schedule the next release, this is not a priority.

**Comment by mjbvz** [comment]
Should have added: anyone is free to look into the problem as well, and I would encourage this if this feature is important to you and you want to see if fixed as soon as possible. The NTVS team can provide help and answer questions to help with any investigations or fixes.

**Comment by mjbvz** [comment]
This Typescript issue seems related: https://github.com/Microsoft/TypeScript/issues/5250 . You can apply custom fonts after setting them by restarting VS:

![image](https://cloud.githubusercontent.com/assets/12821956/16432233/e5ca3c60-3d38-11e6-8f6b-b01ecce6d0b8.png)


Other settings, such as the font background color, get applied right away but text specific settings require a restart (aside: NTVS recommends using magenta Comic Sans for all serious development work.)

I'm looking into the colorization of specific language elements now.

**Comment by mjbvz** [comment]
The Typescript editor uses different colorization properties than our ES5 text editor. The settings are coarser, but here's a mapping from ES5 IntelliSense colors to ES6 IntelliSense colors:

* `Node.js comma` -> `Punctuation`
* `Node.js dot` -> `Punctuation`
* `Node.js grouping` -> `Punctuation`
* `Node.js operator` -> `Operator`

**Comment by mjbvz** [comment]
Fixed by the Typescript team in latest VS2017 ("VS15") builds.

Here's changing the default font:

![image](https://cloud.githubusercontent.com/assets/12821956/19579986/3b69e5e6-96d8-11e6-89be-a1567d4e1d67.png)

And after hitting "OK":

![image](https://cloud.githubusercontent.com/assets/12821956/19580005/56d3af88-96d8-11e6-8dba-e164dc54baaf.png)


You no longer need to reboot VS for the changes to take effect.
